### ISSUE TITLE
获取文件列表时，出现错误

### ISSUE THREAD

**Issue by hhymx** [MrXiaoM/Overflow#105]
### 问题描述

cn.evolvefield.onebot.sdk.util.json.GroupFilesAdapter
22行 fileSize = obj.long("file_size")
没有file_size 应该是size

### 复现

调用group.getFiles().getRoot()

### Overflow 版本

1.0.0.519-0d68f08-SNAPSHOT

### 网络日志

```text
Caused by: com.google.gson.JsonParseException: Can`t find `file_size`
	at cn.evolvefield.onebot.sdk.util.JsonHelperKt.long(JsonHelper.kt:78)
	at cn.evolvefield.onebot.sdk.util.json.GroupFilesAdapter$Files.deserializeFromJson(GroupFilesAdapter.kt:22)
	at cn.evolvefield.onebot.sdk.util.json.GroupFilesAdapter$Files.deserializeFromJson(GroupFilesAdapter.kt:11)
	at cn.evolvefield.onebot.sdk.util.JsonDeserializerKt$DefaultImpls.deserialize(JsonDeserializerKt.kt:12)
	... 124 common frames omitted
```

**Comment by MrXiaoM** [comment]
不是 size，就是 file_size。
Onebot 11 没有文件接口
[go-cqhttp](https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E7%BE%A4%E6%96%87%E4%BB%B6%E8%B5%84%E6%BA%90%E9%93%BE%E6%8E%A5) 是 file_size
![652c2a831ce769eb62718455eec337dd](https://github.com/user-attachments/assets/7f3a99e4-5b12-4737-a476-6829ce3c5063)

相比论坛的回复，你依然**没有按照模板要求**提供更多有效的信息，这个问题不会再继续处理

**Comment by MrXiaoM** [comment]
虽然你没提供信息，我也猜到了，是 NapCat 的问题，他们在这块没遵守 go-cqhttp 的接口规范，自行反馈

**Comment by QianFuv** [comment]
emmm 值得注意的是napcat那边已经修好这个问题了 然后overflow又改了qwq

**Comment by MrXiaoM** [comment]
> emmm 值得注意的是napcat那边已经修好这个问题了 然后overflow又改了qwq

改了并不影响，这是改成了 `file_size` 和 `size` 两个字段都尝试读取

**Comment by QianFuv** [comment]
> > emmm 值得注意的是napcat那边已经修好这个问题了 然后overflow又改了qwq
> 
> 改了并不影响，这是改成了 `file_size` 和 `size` 两个字段都尝试读取

okok 那就没问题了 我放心升级awa
