### ISSUE TITLE
无法成功连接onebot实现

### ISSUE THREAD

**Issue by Viomeat** [MrXiaoM/Overflow#116]
### 问题描述

正向ws和反向ws都会有这个问题
连上llonebot收不到消息 几秒后有了如下的报错

### 复现

启动NTQQ（已安装llonebot）
启动overflow

### Overflow 版本

Overflow v1.0.1.535 正在运行

### 其他组件版本

llonebot v4.4.3
windows ntqq  9.9.16-29804
系统 winserver 2022

### 系统日志

```text
overflow控制台日志：
2024-12-20 15:52:18 I/Onebot: ▌ 反向 WebSocket 客户端 /127.0.0.1:53605 已连接 ┈━═☆
2024-12-20 15:52:18 I/Onebot: 协议端版本信息
{
  "app_name": "LLOneBot",
  "protocol_version": "v11",
  "app_version": "4.4.3"
}
2024-12-20 15:52:25 I/BiliBili Dynamic: github latest version v3.2.12
2024-12-20 15:52:28 W/Onebot: 请求失败: [get_friend_list] 请求失败: app=LLOneBot v4.4.3, message=ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false], retJson={"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-12-20 15:52:28 E/main: Exception in coroutine MiraiConsoleImplementationTerminal
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault, parameter <this>
        at kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault(Iterables.kt)
        at top.mrxiaom.overflow.internal.contact.BotWrapper.updateContacts(BotWrapper.kt:290)
        at top.mrxiaom.overflow.internal.contact.BotWrapper$updateContacts$1.invokeSuspend(BotWrapper.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### 网络日志

```text
2024-12-20 15:52:16 I/Onebot: Overflow v1.0.1.535 正在运行
2024-12-20 15:52:16 I/Onebot: 在端口 12223 开启反向 WebSocket 服务端
2024-12-20 15:52:16 I/Onebot: ▌ 反向 WebSocket 服务端已在 0.0.0.0/0.0.0.0:12223 启动
2024-12-20 15:52:16 I/Onebot: ▌ 正在等待客户端连接...
2024-12-20 15:52:18 I/Onebot: ▌ 反向 WebSocket 客户端 /127.0.0.1:53605 已连接 ┈━═☆
2024-12-20 15:52:18 D/Onebot: [Send] --> {"action":"get_version_info","echo":0}
2024-12-20 15:52:18 D/Onebot: [Recv] <-- {"time":1734681138,"self_id":873817590,"post_type":"meta_event","meta_event_type":"lifecycle","sub_type":"connect"}
2024-12-20 15:52:18 D/Onebot: [Recv] <-- {"status":"ok","retcode":0,"data":{"app_name":"LLOneBot","protocol_version":"v11","app_version":"4.4.3"},"message":"","wording":"","echo":0}
2024-12-20 15:52:18 I/Onebot: 协议端版本信息
{
  "app_name": "LLOneBot",
  "protocol_version": "v11",
  "app_version": "4.4.3"
}
2024-12-20 15:52:18 D/Onebot: [Send] --> {"action":"get_login_info","echo":1}
2024-12-20 15:52:23 D/Onebot: [Recv] <-- {"status":"ok","retcode":0,"data":{"user_id":873817590,"nickname":""},"message":"","wording":"","echo":1}
2024-12-20 15:52:23 D/Onebot: [Send] --> {"action":"get_friend_list","echo":2}
2024-12-20 15:52:28 D/Onebot: [Recv] <-- {"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}
2024-12-20 15:52:28 W/Onebot: 请求失败: [get_friend_list] 请求失败: app=LLOneBot v4.4.3, message=ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false], retJson={"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-12-20 15:52:28 V/Onebot: Stacktrace: 
cn.evolvefield.onebot.client.util.ActionFailedException: 请求失败: app=LLOneBot v4.4.3, message=ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false], retJson={"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}
	at cn.evolvefield.onebot.client.util.ActionSendRequest.send(ActionSendRequest.kt:67)
	at cn.evolvefield.onebot.client.util.ActionSendRequest$send$1.invokeSuspend(ActionSendRequest.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by MrXiaoM** [comment]
```
ntqq api timeout
```
不是 Overflow 的问题
