### ISSUE TITLE
最新构建启动报错

### ISSUE THREAD

**Issue by zzj2039** [MrXiaoM/Overflow#13]
### 问题描述

使用最新构建时启动时报错
`2024-01-24 08:25:56 E/mirai-hibernate-plugin: org.hibernate.MappingException: entity class not found: xyz.cssxsh.mirai.hibernate.entry.FaceRecord
org.hibernate.MappingException: entity class not found: xyz.cssxsh.mirai.hibernate.entry.FaceRecord
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.mapping.PersistentClass.getMappedClass(PersistentClass.java:171)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.internal.BinderHelper.getPropertyOverriddenByMapperOrMapsId(BinderHelper.java:873)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.internal.PropertyBinder.bindBasic(PropertyBinder.java:1016)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.internal.PropertyBinder.bindProperty(PropertyBinder.java:890)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.internal.PropertyBinder.buildProperty(PropertyBinder.java:788)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.internal.PropertyBinder.processElementAnnotations(PropertyBinder.java:709)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.internal.EntityBinder.processIdPropertiesIfNotAlready(EntityBinder.java:1026)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.internal.EntityBinder.handleIdentifier(EntityBinder.java:354)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.internal.EntityBinder.bindEntityClass(EntityBinder.java:234)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.internal.AnnotationBinder.bindClass(AnnotationBinder.java:423)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:256)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:279)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:322)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:129)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:449)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:101)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:910)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:960)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar//xyz.cssxsh.mirai.hibernate.MiraiHibernatePlugin.onEnable(MiraiHibernatePlugin.kt:58)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:244)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:393)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:40)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:54)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:193)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:360)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
Caused by: org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [xyz.cssxsh.mirai.hibernate.entry.FaceRecord]
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:126)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.internal.ClassLoaderAccessImpl.classForName(ClassLoaderAccessImpl.java:67)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.mapping.PersistentClass.getMappedClass(PersistentClass.java:166)
        ... 30 more
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar[shared]//org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:123)
        ... 32 more
Caused by: java.lang.IllegalArgumentException: Serializer for PttMessage can't be registered as a subclass for polymorphic serialization because its kind OPEN is not concrete. To work with multiple hierarchies, register it as a base class.
        at kotlinx.serialization.json.internal.PolymorphismValidator.checkKind(PolymorphismValidator.kt:41)
        at kotlinx.serialization.json.internal.PolymorphismValidator.polymorphic(PolymorphismValidator.kt:31)
        at kotlinx.serialization.modules.SerialModuleImpl.dumpTo(SerializersModule.kt:189)
        at kotlinx.serialization.json.JsonImpl.validateConfiguration(Json.kt:375)
        at kotlinx.serialization.json.JsonImpl.<init>(Json.kt:369)
        at kotlinx.serialization.json.JsonKt.Json(Json.kt:191)
        at kotlinx.serialization.json.JsonKt.Json$default(Json.kt:187)
        at mirai-hibernate-plugin-2.8.0.mirai2.jar//xyz.cssxsh.mirai.hibernate.entry.FaceRecord.<clinit>(FaceRecord.kt:66)
        ... 35 more`

### 复现

添加mirai-hibernate-plugin-2.8.0.mirai2插件，启动报错

### Overflow 版本

2.16.0-19e495b

**Comment by zzj2039** [comment]
`2024-01-25 09:17:51 W/mirai-hibernate-plugin: Exception in Recorder
java.lang.NoClassDefFoundError: net/mamoe/mirai/internal/message/LightMessageRefiner
        at mirai-hibernate-plugin-2.8.0.mirai2.jar//xyz.cssxsh.mirai.hibernate.MiraiHibernateRecorder$record$3.invokeSuspend(MiraiHibernateRecorder.kt:61)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.internal.message.LightMessageRefiner
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.loadClass(JvmPluginClassLoader.kt:503)
        ... 7 more`

**Comment by zzj2039** [comment]
@MrXiaoM

**Comment by MrXiaoM** [comment]
他用了internal的类我没辙，我只保证在 mirai-core-api 下可用
