### ISSUE TITLE
接受到包含 Quote 元素的消息触发 IllegalStateException

### ISSUE THREAD

**Issue by RainyNian** [MrXiaoM/Overflow#20]
### 问题描述

如题

### 复现

在群聊中回复一条消息

### Overflow 版本

Overflow v2.16.0-32355df-SNAPSHOT

### 其他组件版本

onebot实现为 Lagrange.OneBot
https://github.com/LagrangeDev/Lagrange.Core

### 补充信息

[log.txt](https://github.com/MrXiaoM/Overflow/files/14233228/log.txt)

**Comment by RainyNian** [comment]
2024-02-11 12:30:07 W/stderr: Exception in thread "DefaultDispatcher-worker-9" java.lang.NumberFormatException: For input string: "2518984560"
2024-02-11 12:30:07 W/stderr:   at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
2024-02-11 12:30:07 W/stderr:   at java.base/java.lang.Integer.parseInt(Integer.java:662)
2024-02-11 12:30:07 W/stderr:   at java.base/java.lang.Integer.parseInt(Integer.java:778)
2024-02-11 12:30:07 W/stderr:   at top.mrxiaom.overflow.internal.message.OnebotMessages.deserializeFromOneBotJson$overflow_core(OnebotMessages.kt:259)  2024-02-11 12:30:07 W/stderr:   at top.mrxiaom.overflow.internal.message.OnebotMessages.deserializeFromOneBot$overflow_core(OnebotMessages.kt:181)
2024-02-11 12:30:07 W/stderr:   at top.mrxiaom.overflow.internal.message.OnebotMessages.deserializeFromOneBot$overflow_core$default(OnebotMessages.kt:179)                                                                          2024-02-11 12:30:07 W/stder

**Comment by RainyNian** [comment]
似乎还有问题

**Comment by RainyNian** [comment]
询问过 Lagrange.OneBot 的 dev 得到其 ob11 返回的回复 id 为 int 类型

**Comment by RainyNian** [comment]
@MrXiaoM

**Comment by MrXiaoM** [comment]
https://github.com/LagrangeDev/Lagrange.Core/blob/master/Lagrange.OneBot/Core/Message/Entity/ReplySegment.cs#L14

这里类型是 string，onebot 11 给出的例子也是 string
