### ISSUE TITLE
语音消息以及表情无法发出

### ISSUE THREAD

**Issue by onlyzqy** [MrXiaoM/Overflow#27]
### 问题描述

使用Overflow和Lagrange，语音消息无法发出

### 复现

使用overflow-2.16.0-88426f1与Lagrange
发送语音消息以及包含表情的消息无法收到，overflow日志中会显示，但是lagrange日志报错

### Overflow 版本

88426f1

### 其他组件版本

Lagrange-46fc168

### 系统日志

```text
2024-03-06 22:11:02 W/Onebot: Request failed: [send_group_msg, echo=649] , retCode=200
2024-03-06 22:11:02 V/Bot.2411510662: Group(887911271) <- [overflow:audio,file=base64:////lgYAFgAADMAAf/+WBgMyAAAQ4UrjRY... (about 142.18 KB)]
2024-03-06 22:11:02 W/Onebot: Request failed: [send_group_msg, echo=650] , retCode=200
2024-03-06 22:11:02 V/Bot.2411510662: Group(887911271) <- 葡萄油(倒霉一姐の粉)：辛苦了宝宝
【你的宝宝熊紫轶💓@熊紫轶(熊紫轶)】
辛苦你啦！[回头]
```

### 网络日志

```text
2024-03-06 22:11:02 D/Onebot: Client received <-- {"status":"failed","retcode":200,"data":null,"echo":649}
2024-03-06 22:11:02 W/Onebot: Request failed: [send_group_msg, echo=649] , retCode=200
2024-03-06 22:11:02 V/Onebot: Stacktrace: 
cn.evolvefield.onebot.client.util.ActionFailedException: , retCode=200
	at cn.evolvefield.onebot.client.util.ActionSendUtils.send(ActionSendUtils.kt:47)
	at cn.evolvefield.onebot.client.util.ActionSendUtils$send$1.invokeSuspend(ActionSendUtils.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1413)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856)
	at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806)
	at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92)
	at cn.evolvefield.onebot.client.util.ActionSendUtils.onCallback(ActionSendUtils.kt:58)
	at cn.evolvefield.onebot.client.handler.ActionHandler.onReceiveActionResp(ActionHandler.kt:38)
	at cn.evolvefield.onebot.client.connection.IAdapter$DefaultImpls.onReceiveMessage(IAdapter.kt:26)
	at cn.evolvefield.onebot.client.connection.WSClient.onReceiveMessage(WSClient.kt:18)
	at cn.evolvefield.onebot.client.connection.WSClient.onMessage(WSClient.kt:43)
	at top.mrxiaom.overflow.internal.deps.websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636)
	at top.mrxiaom.overflow.internal.deps.websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986)
	at top.mrxiaom.overflow.internal.deps.websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910)
	at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:402)
	at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decode(WebSocketImpl.java:234)
	at top.mrxiaom.overflow.internal.deps.websocket.client.WebSocketClient.run(WebSocketClient.java:516)
	at java.base/java.lang.Thread.run(Thread.java:833)

2024-03-06 22:11:02 D/Onebot: Send to server --> {"action":"send_group_msg","params":{"group_id":887911271,"message":[{"type":"text","data":{"text":"葡萄油(倒霉一姐の粉)："}},{"type":"text","data":{"text":"辛苦了宝宝"}},{"type":"text","data":{"text":"\n【你的宝宝熊紫轶💓@熊紫轶(熊紫轶)】\n"}},{"type":"text","data":{"text":"辛苦你啦！"}},{"type":"face","data":{"id":127}},{"type":"text","data":{"text":""}}],"auto_escape":false},"echo":650}
2024-03-06 22:11:02 D/Onebot: Client received <-- {"status":"failed","retcode":200,"data":null,"echo":650}
2024-03-06 22:11:02 W/Onebot: Request failed: [send_group_msg, echo=650] , retCode=200
2024-03-06 22:11:02 V/Onebot: Stacktrace: 
cn.evolvefield.onebot.client.util.ActionFailedException: , retCode=200
	at cn.evolvefield.onebot.client.util.ActionSendUtils.send(ActionSendUtils.kt:47)
	at cn.evolvefield.onebot.client.util.ActionSendUtils$send$1.invokeSuspend(ActionSendUtils.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1413)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856)
	at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806)
	at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92)
	at cn.evolvefield.onebot.client.util.ActionSendUtils.onCallback(ActionSendUtils.kt:58)
	at cn.evolvefield.onebot.client.handler.ActionHandler.onReceiveActionResp(ActionHandler.kt:38)
	at cn.evolvefield.onebot.client.connection.IAdapter$DefaultImpls.onReceiveMessage(IAdapter.kt:26)
	at cn.evolvefield.onebot.client.connection.WSClient.onReceiveMessage(WSClient.kt:18)
	at cn.evolvefield.onebot.client.connection.WSClient.onMessage(WSClient.kt:43)
	at top.mrxiaom.overflow.internal.deps.websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636)
	at top.mrxiaom.overflow.internal.deps.websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986)
	at top.mrxiaom.overflow.internal.deps.websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910)
	at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:402)
	at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decode(WebSocketImpl.java:234)
	at top.mrxiaom.overflow.internal.deps.websocket.client.WebSocketClient.run(WebSocketClient.java:516)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by MrXiaoM** [comment]
Lagrange send message retCode=200
#26
