### ISSUE TITLE
群聊信息中`Member`的`Card`应该可为空

### ISSUE THREAD

**Issue by EvolvedGhost** [MrXiaoM/Overflow#47]
### 问题描述

部分插件调用`Member.getNameCard()`会报错，稍微排查了下应该是 ad8e502 里切换成Kotlin强类型绑定导致的，最后一个无此现象的snapshot版本为 f4dfdfe 。

同时查阅Onebot的日志，目前`card`和`title`可为空

### 复现

在插件中使用`Member.getNameCard()`，下方以petpet为例

### Overflow 版本

 f454a28

### 其他组件版本

应该与其他组件没关系

### 系统日志

```text
An exception occurred when processing event. Subscriber scope: '<unnamed>'. Broadcaster scope: 'Bot.{BOTID}.EventDispatcher'. Onebot implementation: 'Lagrange.OneBot v0.0.3'
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because the return value of "net.mamoe.mirai.contact.Member.getNameCard()" is null
	at petpet-6.1.mirai2.jar//moe.dituon.petpet.mirai.MiraiPetpet.getNameOrNick(MiraiPetpet.java:551)
	at petpet-6.1.mirai2.jar//moe.dituon.petpet.mirai.MiraiPetpet.responseMessage(MiraiPetpet.java:197)
	at petpet-6.1.mirai2.jar//moe.dituon.petpet.mirai.MiraiPetpet.onGroupMessage(MiraiPetpet.java:158)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### 网络日志

```text
{"group_id":GID,"user_id":UID,"nickname":"NAME","card":null,"sex":"","age":0,"area":"","join_time":1680000000,"last_sent_time":1780000000,"level":"24","role":"member","unfriendly":false,"title":null,"title_expire_time":0,"card_changeable":false}
```

**Comment by EvolvedGhost** [comment]
https://github.com/MrXiaoM/Overflow/blob/main/onebot/src/main/kotlin/sdk/response/group/GroupMemberInfoResp.kt

目前我觉得是这个地方有问题，目前`card`和`title`都是`String!`，但是设计这俩的地方好像挺多的，不敢乱动

**Comment by MrXiaoM** [comment]
感觉是 Gson 跟 kotlin 的兼容性问题，我没想到 null 是可以赋值到 kotlin 的非空字段里的，等有空我统一处理一下这个问题

**Comment by MrXiaoM** [comment]
```kotlin
// GroupMemberInfoResp: 44
    override fun toString(): String {
        return "GroupMemberInfoResp(groupId=$groupId, userId=$userId, nickname='$nickname', card='$card', sex='$sex', age=$age, area='$area', joinTime=$joinTime, lastSentTime=$lastSentTime, level=$level, role='$role', unfriendly=$unfriendly, title='$title', titleExpireTime=$titleExpireTime, cardChangeable=$cardChangeable, shutUpTimestamp=$shutUpTimestamp)"
    }
// JsonHelper: 114
inline fun <reified T : Any> JsonObject.fromJson(key: String): T? {
    return gson.fromJson(this[key].deepCopyIgnoreNulls(), T::class.java)
}
inline fun <reified T : Any> JsonObject.fromJsonOld(key: String): T? {
    return gson.fromJson(this[key], T::class.java)
}
fun main() {
    val json = JsonParser.parseString("{\"data\":{\"user_id\":114514,\"card\":null}}").asJsonObject
    println(json)
    val old = json.fromJsonOld<GroupMemberInfoResp>("data")
    val new = json.fromJson<GroupMemberInfoResp>("data")
    println("Old: $old")
    println("New: $new")
}
```

```
{"data":{"user_id":114514,"card":null}}
Old: GroupMemberInfoResp(groupId=0, userId=114514, nickname='', card='null', sex='', age=0, area='', joinTime=0, lastSentTime=0, level=0, role='member', unfriendly=false, title='', titleExpireTime=0, cardChangeable=true, shutUpTimestamp=0)
New: GroupMemberInfoResp(groupId=0, userId=114514, nickname='', card='', sex='', age=0, area='', joinTime=0, lastSentTime=0, level=0, role='member', unfriendly=false, title='', titleExpireTime=0, cardChangeable=true, shutUpTimestamp=0)

```

测试通过

**Comment by EvolvedGhost** [comment]
更新最新版本后petpet依然报错，检查了下petpet的逻辑写了套报错的实例代码
```
@Override
    public void onEnable() {
        getLogger().info("Plugin loaded!");
        GlobalEventChannel.INSTANCE.subscribeAlways(GroupMessageEvent.class, event->{
            System.out.println("===ENTER TEST===");
            Member m = event.getGroup().getBotAsMember();
            System.out.print("NameCard is: ");
            System.out.println(m.getNameCard());
            System.out.print("Nick is: ");
            System.out.println(m.getNick());
            try{
                String test = m.getNameCard().isEmpty() ? m.getNick() : m.getNameCard();
                System.out.println(test);
            }catch (Exception e){
                e.printStackTrace();
            }
            System.out.println("===END TEST===");
        });
    }
```

日志如下：
```
2024-05-15 17:15:56 I/stdout: ===ENTER TEST===
2024-05-15 17:15:56 I/stdout: NameCard is: null
2024-05-15 17:15:56 I/stdout: Nick is: BOTNICK
2024-05-15 17:15:56 W/stderr: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because the return value of "net.mamoe.mirai.contact.Member.getNameCard()" is null
2024-05-15 17:15:56 W/stderr:   at demo-0.1.0.mirai2.jar//com.example.Demo.lambda$onEnable$0(Demo.java:31)
2024-05-15 17:15:56 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605)
2024-05-15 17:15:56 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605)
2024-05-15 17:15:56 W/stderr:   at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
2024-05-15 17:15:56 W/stderr:   at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
2024-05-15 17:15:56 W/stderr:   at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
2024-05-15 17:15:56 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-05-15 17:15:56 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-05-15 17:15:56 W/stderr:   at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2024-05-15 17:15:56 W/stderr:   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2024-05-15 17:15:56 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-05-15 17:15:56 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-05-15 17:15:56 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-05-15 17:15:56 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-05-15 17:15:56 I/stdout: ===END TEST===
```

`Group.getBotAsMember()`这个函数以某种形式依然获取了null到card里

**Comment by MrXiaoM** [comment]
```
2024-05-18 17:06:59 I/stdout: ===ENTER TEST===
2024-05-18 17:06:59 I/stdout: NameCard is:
2024-05-18 17:06:59 I/stdout: Nick is: 电子
2024-05-18 17:06:59 I/stdout: 电子
2024-05-18 17:06:59 I/stdout: ===END TEST===
```
在新版本中测试通过

**Comment by EvolvedGhost** [comment]
> ```
> 2024-05-18 17:06:59 I/stdout: ===ENTER TEST===
> 2024-05-18 17:06:59 I/stdout: NameCard is:
> 2024-05-18 17:06:59 I/stdout: Nick is: 电子
> 2024-05-18 17:06:59 I/stdout: 电子
> 2024-05-18 17:06:59 I/stdout: ===END TEST===
> ```
> 
> 在新版本中测试通过

估计是Lagrange的兼容性问题，我去看了下新版本依然存在这个问题，看了下当前的逻辑是这样：

```
2024-05-18 18:49:49 I/Onebot: 服务端版本信息
{
  "status": "ok",
  "retcode": 0,
  "data": {
    "app_name": "Lagrange.OneBot",
    "app_version": "0.0.3",
    "protocol_version": "v11",
    "nt_protocol": "Linux | 3.1.2-13107"
  },
  "echo": 0
}


2024-05-18 18:49:54 D/Onebot: Client received <-- 
{
    "message_type": "group",
    "sub_type": "normal",
    "message_id": 942040339,
    "group_id": 12345,
    "user_id": 88888,
    "anonymous": null,
    "message": [
        {
            "type": "text",
            "data": {
                "text": "3"
            }
        }
    ],
    "raw_message": "3",
    "font": 0,
    "sender": {
        "user_id": 88888,
        "nickname": "E710",
        "card": "username",
        "sex": "unknown",
        "age": 0,
        "area": "",
        "level": "100",
        "role": "owner",
        "title": ""
    },
    "time": 1716029394,
    "self_id": 77777,
    "post_type": "message"
}


2024-05-18 18:49:54 D/Onebot: Send to server --> 
{
    "action": "get_group_member_list",
    "params": {
        "group_id": 12345
    },
    "echo": 4
}


2024-05-18 18:49:54 D/Onebot: Client received <-- 
{
    "status": "ok",
    "retcode": 0,
    "data": [
        {
            "group_id": 12345,
            "user_id": 66666,
            "nickname": "Q群管家",
            "card": null,
            "sex": "",
            "age": 0,
            "area": "",
            "join_time": 1671523796,
            "last_sent_time": 1671524715,
            "level": "0",
            "role": "member",
            "unfriendly": false,
            "title": null,
            "title_expire_time": 0,
            "card_changeable": false
        },
        {
            "group_id": 12345,
            "user_id": 88888,
            "nickname": "ID",
            "card": "username",
            "sex": "",
            "age": 0,
            "area": "",
            "join_time": 1565643645,
            "last_sent_time": 1715932682,
            "level": "100",
            "role": "owner",
            "unfriendly": false,
            "title": "芝士群主",
            "title_expire_time": 0,
            "card_changeable": false
        },
        {
            "group_id": 12345,
            "user_id": 77777,
            "nickname": "芝士BOT",
            "card": null,
            "sex": "",
            "age": 0,
            "area": "",
            "join_time": 1697010760,
            "last_sent_time": 1715932682,
            "level": "43",
            "role": "member",
            "unfriendly": false,
            "title": null,
            "title_expire_time": 0,
            "card_changeable": false
        }
    ],
    "echo": 4
}


2024-05-18 18:49:55 D/Onebot: Client received <-- 
{
    "message_type": "group",
    "sub_type": "normal",
    "message_id": 942088876,
    "group_id": 12345,
    "user_id": 88888,
    "anonymous": null,
    "message": [
        {
            "type": "text",
            "data": {
                "text": "3"
            }
        }
    ],
    "raw_message": "3",
    "font": 0,
    "sender": {
        "user_id": 88888,
        "nickname": "ID",
        "card": "username",
        "sex": "unknown",
        "age": 0,
        "area": "",
        "level": "100",
        "role": "owner",
        "title": "芝士群主"
    },
    "time": 1716029395,
    "self_id": 77777,
    "post_type": "message"
}


2024-05-18 18:49:55 D/Onebot: Client received <-- 
{
    "message_type": "group",
    "sub_type": "normal",
    "message_id": 942189006,
    "group_id": 12345,
    "user_id": 88888,
    "anonymous": null,
    "message": [
        {
            "type": "text",
            "data": {
                "text": "3"
            }
        }
    ],
    "raw_message": "3",
    "font": 0,
    "sender": {
        "user_id": 88888,
        "nickname": "ID",
        "card": "username",
        "sex": "unknown",
        "age": 0,
        "area": "",
        "level": "100",
        "role": "owner",
        "title": "芝士群主"
    },
    "time": 1716029395,
    "self_id": 77777,
    "post_type": "message"
}
```

也就是`Group.getBotAsMember()`的信息其实是`get_group_member_list`来的

`get_group_member_list`是在`Bot.kt`里

然后我参考上次修复其他为空的方法改了下这里

https://github.com/MrXiaoM/Overflow/blob/de5585c6fdff4f8cd3fd90f43b6aa1df211e3ce8/onebot/src/main/kotlin/client/core/Bot.kt#L1466-L1472

改成：

```
inline fun <reified T> JsonElement.withToken(): T {
    return gson.fromJson(this.deepCopyIgnoreNulls(), object : TypeToken<T>() {}.type)
}

inline fun <reified T> JsonElement.withClass(): T {
    return gson.fromJson(this.deepCopyIgnoreNulls(), T::class.java)
}
```

现在正常了，这样改应该没啥问题，您再看看

**Comment by MrXiaoM** [comment]
好的
