### ISSUE TITLE
无法正确接收到消息

### ISSUE THREAD

**Issue by IndigoRCS** [MrXiaoM/Overflow#6]
在群里发送了一条消息，bot本应接收到该消息并作出响应（通过mirai-api-http连接）
刚启动的时候是可以正确响应的，但是过了一段时间后发现bot并没有做出响应，疑似是没有正确接收到消息

在`logs/onebot`文件夹下有接收到该消息的日志
```shell
2023-12-06 19:06:55 D/Onebot: Client received <-- {"time":1701860814,"self_id":,"post_type":"message","message_type":"group","sub_type":"normal","message_id":,"group_id":,"peer_id":,"user_id":,"message":[{"data":{"text":"查询"},"type":"text"}],"raw_message":"查询","font":0,"sender":{"user_id":,"nickname":"","card":"","role":"owner","title":"","level":""}}
```

但是在`logs`文件夹下没有任何接收到该消息的日志，最后一条日志是
```shell
2023-12-06 14:59:41 I/Onebot: ▌ 反向 WebSocket 客户端 /host:port 已连接 ┈━═☆
```

在`bots/[QQ]/log`目录下也没有接收到该消息的日志，最后一条日志是上一次接收到消息的日志（也就是说，之前是可以正常接收到消息的，但是后来不行了）

mirai-api-http：2.9.1
Overflow版本：3fefc93c3fb994480cec78ca524d8579c500821a

**Comment by MrXiaoM** [comment]
你的json是错的，不存在 `: ,` 这种语法

**Comment by IndigoRCS** [comment]
> 你的json是错的，不存在 `: ,` 这种语法

那个是我手动删除了一些敏感信息（比如QQ号什么的），原始日志语法是正确的

**Comment by MrXiaoM** [comment]
> 那个是我手动删除了一些敏感信息（比如QQ号什么的），原始日志语法是正确的

连接 Overflow 的实现是什么

**Comment by IndigoRCS** [comment]
> 连接 Overflow 的实现是什么

OpenShamrock v1.0.7dev

**Comment by MrXiaoM** [comment]
> 刚启动的时候是可以正确响应的，但是过了一段时间后发现bot并没有做出响应

发送你的完整日志，以便查看中间发生了什么

**Comment by IndigoRCS** [comment]
脱敏之后的log：



`bots/[QQ]/logs`：

```
2023-12-06 12:08:07 V/Bot.【QQ号】: Event: BotOnlineEvent(bot=top.mrxiaom.overflow.internal.contact.BotWrapper@7a682d35)
2023-12-06 12:25:46 V/Bot.【QQ号】: [【群名】(【群号】)] 【昵称】(【QQ号】) -> 【消息1】
2023-12-06 12:38:55 V/Bot.【QQ号】: [【群名】(【群号】)] 【昵称】(【QQ号】) -> 【消息2】
2023-12-06 12:52:16 V/Bot.【QQ号】: [【群名】(【群号】)] 【昵称】(【QQ号】) -> 【消息3】
2023-12-06 19:29:07 I/Bot.【QQ号】: Bot cancelled: Job was cancelled
```

`logs`：

```
2023-12-06 12:08:01 I/main: Starting mirai-console...
2023-12-06 12:08:01 I/main: 

===================================[ Mirai console 2.16.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-12-06 12:08:01 I/main: Backend: version 2.16.0, built on 2023-10-20 06:28:10.
2023-12-06 12:08:01 I/main: Frontend Terminal: version 2.16.0, provided by Mamoe Technologies
2023-12-06 12:08:01 I/main: Welcome to visit https://mirai.mamoe.net/
2023-12-06 12:08:02 I/plugin: Successfully loaded plugin mirai-api-http v2.9.1
2023-12-06 12:08:03 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-12-06 12:08:03 I/Onebot: Overflow v2.16.0-3fefc93 正在运行
2023-12-06 12:08:03 I/Onebot: 在端口 【host】:【port】 开启反向 WebSocket 服务端
2023-12-06 12:08:03 I/Onebot: ▌ 反向 WebSocket 服务端已在 0.0.0.0/0.0.0.0:【port】 启动
2023-12-06 12:08:03 I/Onebot: ▌ 正在等待客户端连接...
2023-12-06 12:08:06 I/Onebot: ▌ 反向 WebSocket 客户端 /【host】:【port】 已连接 ┈━═☆
2023-12-06 12:08:06 I/Onebot: 服务端版本信息
{
  "status": "ok",
  "retcode": 0,
  "data": {
    "app_full_name": "Shamrock v1.0.7-dev.6201d12",
    "app_name": "Shamrock",
    "app_version": "1.0.7-dev.6201d12",
    "impl": "shamrock",
    "version": "1.0.7-dev.6201d12",
    "onebot_version": "11"
  },
  "echo": 0
}
2023-12-06 12:08:07 V/Bot.【QQ号】: Event: BotOnlineEvent(bot=top.mrxiaom.overflow.internal.contact.BotWrapper@7a682d35)
2023-12-06 12:08:07 I/Mirai HTTP API: ********************************************************
2023-12-06 12:08:07 I/MahKtorAdapter[http,ws]: Autoreload is disabled because the development mode is off.
2023-12-06 12:08:07 I/MahKtorAdapter[http,ws]: Application started in 0.168 seconds.
2023-12-06 12:08:07 I/MahKtorAdapter[http,ws]: Responding at http://【host】:【port】
2023-12-06 12:08:07 I/http adapter: >>> [http adapter] is listening at http://【host】:【port】
2023-12-06 12:08:07 I/ws adapter: >>> [ws adapter] is listening at ws://【host】:【port】
2023-12-06 12:08:07 I/Mirai HTTP API: Http api server is running with verifyKey: overflow-2.16
2023-12-06 12:08:07 I/Mirai HTTP API: adaptors: [http,ws]
2023-12-06 12:08:07 I/Mirai HTTP API: ********************************************************
2023-12-06 12:08:07 I/main: 3 plugin(s) enabled.
2023-12-06 12:08:07 I/main: mirai-console started successfully.
2023-12-06 12:25:46 V/Bot.【QQ号】: [【群名】(【群号】)] 【昵称】(【QQ号】) -> 【消息1】
2023-12-06 12:38:55 V/Bot.【QQ号】: [【群名】(【群号】)] 【昵称】(【QQ号】) -> 【消息2】
2023-12-06 12:52:16 V/Bot.【QQ号】: [【群名】(【群号】)] 【昵称】(【QQ号】) -> 【消息3】
2023-12-06 13:07:15 I/Onebot: ▌ 反向 WebSocket 客户端 null 连接因  已关闭
2023-12-06 13:07:17 I/Onebot: ▌ 反向 WebSocket 客户端 /【host】:【port】 已连接 ┈━═☆
2023-12-06 13:07:32 I/Onebot: ▌ 反向 WebSocket 客户端 null 连接因  已关闭
2023-12-06 13:07:33 I/Onebot: ▌ 反向 WebSocket 客户端 /【host】:【port】 已连接 ┈━═☆
2023-12-06 13:49:58 I/Onebot: ▌ 反向 WebSocket 客户端 null 连接因  已关闭
2023-12-06 13:49:59 I/Onebot: ▌ 反向 WebSocket 客户端 /【host】:【port】 已连接 ┈━═☆
2023-12-06 14:59:40 I/Onebot: ▌ 反向 WebSocket 客户端 null 连接因  已关闭
2023-12-06 14:59:41 I/Onebot: ▌ 反向 WebSocket 客户端 /【host】:【port】 已连接 ┈━═☆
```



`logs/onebot`：

```
2023-12-06 12:08:03 I/Onebot: Overflow v2.16.0-3fefc93 正在运行
2023-12-06 12:08:03 I/Onebot: 在端口 【port】 开启反向 WebSocket 服务端
2023-12-06 12:08:03 I/Onebot: ▌ 反向 WebSocket 服务端已在 0.0.0.0/0.0.0.0:【port】 启动
2023-12-06 12:08:03 I/Onebot: ▌ 正在等待客户端连接...
2023-12-06 12:08:06 I/Onebot: ▌ 反向 WebSocket 客户端 /【host】:【port】 已连接 ┈━═☆
2023-12-06 12:08:06 D/Onebot: Send to server --> {"action":"get_version_info","echo":0}
2023-12-06 12:08:06 D/Onebot: Client received <-- {"time":1701835686,"self_id":【QQ号】,"post_type":"meta_event","meta_event_type":"lifecycle","sub_type":"connect","status":{"self":{"platform":"qq","user_id":【QQ号】},"online":true,"good":true,"qq.status":"正常"},"interval":15000}
2023-12-06 12:08:06 D/Onebot: Client received <-- {"status":"ok","retcode":0,"data":{"app_full_name":"Shamrock v1.0.7-dev.6201d12","app_name":"Shamrock","app_version":"1.0.7-dev.6201d12","impl":"shamrock","version":"1.0.7-dev.6201d12","onebot_version":"11"},"echo":0}
2023-12-06 12:08:06 I/Onebot: 服务端版本信息
{
  "status": "ok",
  "retcode": 0,
  "data": {
    "app_full_name": "Shamrock v1.0.7-dev.6201d12",
    "app_name": "Shamrock",
    "app_version": "1.0.7-dev.6201d12",
    "impl": "shamrock",
    "version": "1.0.7-dev.6201d12",
    "onebot_version": "11"
  },
  "echo": 0
}

【此处省略初始时的一些收发，例如get_login_info、get_friend_list……】
【此处省略几条形如下面两行的重连消息】
2023-12-06 14:59:40 I/Onebot: ▌ 反向 WebSocket 客户端 null 连接因  已关闭
2023-12-06 14:59:41 I/Onebot: ▌ 反向 WebSocket 客户端 /【host】:【port】 已连接 ┈━═☆
【此处省略大量收到的群消息，格式与下面最后这条一样】

2023-12-06 19:06:55 D/Onebot: Client received <-- {"time":1701860814,"self_id":【QQ号】,"post_type":"message","message_type":"group","sub_type":"normal","message_id":【message_id】,"group_id":【群号】,"peer_id":【QQ号】,"user_id":【用户QQ】,"message":[{"data":{"text":"查询"},"type":"text"}],"raw_message":"查询","font":0,"sender":{"user_id":【用户QQ】,"nickname":"【用户昵称】","card":"【用户昵称】","role":"owner","title":"","level":""}}
```

**Comment by IndigoRCS** [comment]
使用最新构建遇到以下错误
```
2023-12-11 14:15:35 E/top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl: generated frame is invalid
top.mrxiaom.overflow.internal.deps.websocket.exceptions.InvalidDataException: Trying to send an illegal close code!
        at top.mrxiaom.overflow.internal.deps.websocket.framing.CloseFrame.isValid(CloseFrame.java:237)
        at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.close(WebSocketImpl.java:490)
        at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.close(WebSocketImpl.java:516)
        at cn.evolvefield.onebot.client.connection.WSServer.onOpen(WSServer.kt:55)
        at top.mrxiaom.overflow.internal.deps.websocket.server.WebSocketServer.onWebsocketOpen(WebSocketServer.java:724)
        at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.open(WebSocketImpl.java:767)
        at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:308)
        at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decode(WebSocketImpl.java:237)
        at top.mrxiaom.overflow.internal.deps.websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1114)
        at top.mrxiaom.overflow.internal.deps.websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1086)

2023-12-11 14:15:35 E/Onebot: ▌ 反向 WebSocket 客户端连接出现错误 Trying to send an illegal close code! 或未连接 ┈━═☆
2023-12-11 14:15:35 I/Onebot: ▌ 反向 WebSocket 客户端连接因 generated frame is invalid 已关闭
```

Overflow: overflow-core-all-6260296
OpenShamrock: Shamrock-v1.0.7-dev.5776524-all

**Comment by MrXiaoM** [comment]
> 使用最新构建遇到以下错误
> ```
> 2023-12-11 14:15:35 E/top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl: generated frame is invalid
> top.mrxiaom.overflow.internal.deps.websocket.exceptions.InvalidDataException: Trying to send an illegal close code!
>         at top.mrxiaom.overflow.internal.deps.websocket.framing.CloseFrame.isValid(CloseFrame.java:237)
>         at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.close(WebSocketImpl.java:490)
>         at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.close(WebSocketImpl.java:516)
>         at cn.evolvefield.onebot.client.connection.WSServer.onOpen(WSServer.kt:55)
>         at top.mrxiaom.overflow.internal.deps.websocket.server.WebSocketServer.onWebsocketOpen(WebSocketServer.java:724)
>         at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.open(WebSocketImpl.java:767)
>         at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:308)
>         at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decode(WebSocketImpl.java:237)
>         at top.mrxiaom.overflow.internal.deps.websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1114)
>         at top.mrxiaom.overflow.internal.deps.websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1086)
> 
> 2023-12-11 14:15:35 E/Onebot: ▌ 反向 WebSocket 客户端连接出现错误 Trying to send an illegal close code! 或未连接 ┈━═☆
> 2023-12-11 14:15:35 I/Onebot: ▌ 反向 WebSocket 客户端连接因 generated frame is invalid 已关闭
> ```
> 
> Overflow: overflow-core-all-6260296
> OpenShamrock: Shamrock-v1.0.7-dev.5776524-all

access token 错误

**Comment by IndigoRCS** [comment]
检查了一下，`overflow.json`的`token`字段和OpenShamrock里的鉴权token设置的是一样的

而且在更新新版overflow之前是可以正常连接的

**Comment by IndigoRCS** [comment]
删除token确实能连上了，但是最好还是有鉴权比较好吧

**Comment by MrXiaoM** [comment]
> 删除token确实能连上了，但是最好还是有鉴权比较好吧

https://github.com/whitechi73/OpenShamrock/blob/master/xposed/src/main/java/moe/fuqiuluo/shamrock/xposed/actions/InitRemoteService.kt#L66

找到原因了，他的 bearer 是小写的，我检验的是大写的（

**Comment by IndigoRCS** [comment]
使用最新构建成功解决鉴权问题和重连之后无法收到消息的问题

非常感谢！
