### ISSUE TITLE
希望能够添加日志简化功能

### ISSUE THREAD

**Issue by Travellerrr** [MrXiaoM/Overflow#61]
由于某种原因，我所部署的 mirai 与 NapCat 不在同一服务器之内，每次传递文件或者图片消息时会被转换成base64编码发送，同时日志内会记录完整的编码信息。这导致每次日志会占用大量无用空间且可读性降低，目前最多已经达到了1天1GB的日志存储量。
![image](https://github.com/MrXiaoM/Overflow/assets/139743802/c29565ad-112f-4f87-bcf6-7399bb92e36d)

所以希望能够添加一个日志简化功能，可以在配置文件里面启用，使日志保存类似于后台 `[overflow:image,url=base64://xxx... (png, about 12.34 KB)]`的简化overflow码，拯救我的硬盘空间(bushi
十分感谢！

**Comment by MrXiaoM** [comment]
see [LocalFileService](https://github.com/MrXiaoM/LocalFileService).

**Comment by MrXiaoM** [comment]
> 不在同一服务器

可修改 LocalFileService 使其通过网络接口传输

**Comment by Travellerrr** [comment]
```java
2024-06-26 18:28:56 W/Onebot: 请求失败: [send_group_msg] 请求失败: app=NapCat.Onebot v1.4.7, message=Error: ENOENT: no such file or directory, open '//home/container/data/top.mrxiaom.overflow-local-file-service/78e22b3d-21fe-410c-9099-ce8b76ed7998.png', retJson={"status":"failed","retcode":1200,"data":null,"message":"Error: ENOENT: no such file or directory, open '//home/container/data/top.mrxiaom.overflow-local-file-service/78e22b3d-21fe-410c-9099-ce8b76ed7998.png'","wording":"Error: ENOENT: no such file or directory, open '//home/container/data/top.mrxiaom.overflow-local-file-service/78e22b3d-21fe-410c-9099-ce8b76ed7998.png'","echo":9}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-06-26 18:28:56 V/Bot.xxx: Group(xxx) <- [overflow:image,url=file:////home/container/data/top.mrxiaom.overflow-local-file-service/78e22b3d-21fe-410c-9099-ce8b76ed7998.png]
2024-06-26 18:28:56 E/HuYanEconomy: 壶言经济--Exception in EventHandler
net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:155)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:26)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternal$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:162)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:148)
        ... 10 more
Caused by: java.lang.IllegalStateException: 消息发送失败，详见网络日志 (logs/onebot/*.log) 和 Onebot 实现 (NapCat.Onebot v1.4.7) 的日志
        at top.mrxiaom.overflow.internal.utils.TransformerUtilsKt.safeMessageIds(TransformerUtils.kt:97)
        at top.mrxiaom.overflow.internal.contact.GroupWrapper.sendMessage(GroupWrapper.kt:176)
        at top.mrxiaom.overflow.internal.contact.GroupWrapper$sendMessage$1.invokeSuspend(GroupWrapper.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1413)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856)
        at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806)
        at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92)
        at cn.evolvefield.onebot.client.util.ActionSendRequest.onCallback(ActionSendRequest.kt:80)
        at cn.evolvefield.onebot.client.handler.ActionHandler.onReceiveActionResp(ActionHandler.kt:41)
        at cn.evolvefield.onebot.client.connection.IAdapter$DefaultImpls.onReceiveMessage(IAdapter.kt:27)
        at cn.evolvefield.onebot.client.connection.WSClient.onReceiveMessage(WSClient.kt:19)
        at cn.evolvefield.onebot.client.connection.WSClient.onMessage(WSClient.kt:51)
        at top.mrxiaom.overflow.internal.deps.websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636)
        at top.mrxiaom.overflow.internal.deps.websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986)
        at top.mrxiaom.overflow.internal.deps.websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910)
        at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:402)
        at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decode(WebSocketImpl.java:234)
        at top.mrxiaom.overflow.internal.deps.websocket.client.WebSocketClient.run(WebSocketClient.java:516)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

麻烦问一下，为什么获取路径时会获取的 `//home/container/data/top.mrxiaom.overflow-local-file-service/图片` 呢？是我设置不对吗

**Comment by MrXiaoM** [comment]
> 麻烦问一下，为什么获取路径时会获取的 `//home/container/data/top.mrxiaom.overflow-local-file-service/图片` 呢？是我设置不对吗

是部署在同一台机器上吗，是的话等我推更新修复，这个插件我还没在 Linux 上测试过。
不是的话等我把远程版本的写好

**Comment by Travellerrr** [comment]
> > 麻烦问一下，为什么获取路径时会获取的 `//home/container/data/top.mrxiaom.overflow-local-file-service/图片` 呢？是我设置不对吗
> 
> 是部署在同一台机器上吗，是的话等我推更新修复，这个插件我还没在 Linux 上测试过。 不是的话等我把远程版本的写好

不是的，是在两台不同服务器上，那我再等等远程版本吧。感谢
