### ISSUE TITLE
Overflow在FriendNudgeEvent事件尝试去获取GroupID

### ISSUE THREAD

**Issue by 0XPYEX0** [MrXiaoM/Overflow#66]
### 问题描述

如题，在FriendNudgeEvent事件尝试去获取了群ID  ~(那肯定是获取不到)~

### 复现

在私聊戳一戳bot，然后报错(群聊QQNT暂不支持)

### Overflow 版本

9132e58

### 其他组件版本

[Lagrange](https://github.com/LagrangeDev/Lagrange.Core/actions/runs/9747033492)

### 系统日志

**Lagrange**
(其实Lagrange只是正常触发消息)
```
info: Lagrange.OneBot.Core.Notify.NotifyService[0]
      [04:01:17] FriendPokeEvent: My_QQ_ID
```

**Overflow**
```
2024-07-06 03:42:59 W/Onebot: 请求失败: [get_group_info] 请求失败: app=Lagrange.OneBot v0.0.3, message=, retJson={"status":"failed","retcode":-1,"data":null,"echo":7}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-07-06 03:42:59 W/stderr: Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalStateException: 无法取得群 0 的信息
2024-07-06 03:42:59 W/stderr:   at top.mrxiaom.overflow.internal.utils.TransformerUtilsKt.group(TransformerUtils.kt:64)
2024-07-06 03:42:59 W/stderr:   at top.mrxiaom.overflow.internal.utils.TransformerUtilsKt$group$1.invokeSuspend(TransformerUtils.kt)
2024-07-06 03:42:59 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-07-06 03:42:59 W/stderr:   at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
2024-07-06 03:42:59 W/stderr:   at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2024-07-06 03:42:59 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2024-07-06 03:42:59 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-07-06 03:42:59 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-07-06 03:42:59 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-07-06 03:42:59 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-07-06 03:42:59 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-07-06 03:42:59 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(overflow), StandaloneCoroutine{Cancelling}@636e0bd3, Dispatchers.Default]
```

### 网络日志

```
2024-07-06 04:01:17 D/Onebot: [Recv] <-- {"sub_type":"poke","sender_id":OwnerID,"user_id":OwnerID,"target_id":BotID,"notice_type":"notify","time":1720209677,"self_id":BotID,"post_type":"notice"}

2024-07-06 04:01:17 D/Onebot: [Send] --> {"action":"get_group_info","params":{"group_id":0,"no_cache":false},"echo":9}

2024-07-06 04:01:17 D/Onebot: [Recv] <-- {"status":"failed","retcode":-1,"data":null,"echo":9}
2024-07-06 04:01:17 W/Onebot: 请求失败: [get_group_info] 请求失败: app=Lagrange.OneBot v0.0.3, message=, retJson={"status":"failed","retcode":-1,"data":null,"echo":9}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-07-06 04:01:17 V/Onebot: Stacktrace: 
cn.evolvefield.onebot.client.util.ActionFailedException: 请求失败: app=Lagrange.OneBot v0.0.3, message=, retJson={"status":"failed","retcode":-1,"data":null,"echo":9}
	at cn.evolvefield.onebot.client.util.ActionSendRequest.send(ActionSendRequest.kt:67)
	at cn.evolvefield.onebot.client.util.ActionSendRequest$send$1.invokeSuspend(ActionSendRequest.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by 0XPYEX0** [comment]
我爱你🥰
