### ISSUE TITLE
BotUtils 中非法HTTP的请求方式 'get'

### ISSUE THREAD

**Issue by HatoYuze** [MrXiaoM/Overflow#68]
### 操作
 在`mirai-core` 中获取 `GroupActive`

 在运行代码时，发现该操作会出现意料之外的返回，抛出错误 `java.net.ProtocolException: Invalid HTTP method: get`

个人认为这是因为 [https://github.com/MrXiaoM/Overflow/blob/main/overflow-core/src/main/kotlin/top/mrxiaom/overflow/internal/utils/BotUtils.kt#L84](BotUtils.kt#84) 所导致的问题

更换`s01.oss.sonatype.org`最新版后仍存在该问题 遂提出该issue

### 复现

```kotlin
object Example : SimpleListenerHost() {
    val logger = MiraiLogger.Factory.create(Example::class)
    override fun handleException(context: CoroutineContext, exception: Throwable) {
        logger.error(exception)
    }
    
    @EventHandler
    suspend fun GroupMemberEvent.listener() {
        println(group.active.queryActiveRank())
    }
}
```

监听到群聊信息事件时会抛出错误

### Overflow 版本

2.16.0-febc5da-20240401.041614-1

### 其他组件版本

mirai-core & mirai-console: `2.16.0`

Jdk:
`bcprov-jdk15on-1.64`

Onebot:
[https://github.com/LagrangeDev/Lagrange.Core/actions/runs/9819143385](Lagrange.Onebot_win-x64_8.0)

### 系统日志

```text
java.net.ProtocolException: Invalid HTTP method: get
        at java.base/java.net.HttpURLConnection.setRequestMethod(HttpURLConnection.java:491)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.setRequestMethod(HttpURLConnection.java:598)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.setRequestMethod(HttpsURLConnectionImpl.java:343)
        at top.mrxiaom.overflow.internal.utils.BotUtilsKt$httpGet$2.invokeSuspend(BotUtils.kt:84)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by HatoYuze** [comment]
自己改了一下..
发现除了`get`以外还有别的问题
```
java.io.FileNotFoundException: https://qun.qq.com/cgi-bin/honorv2/honor_title_list?group_code=5*******7&request_type=2&g_tk=1********0
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2010)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1615)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
        at top.mrxiaom.overflow.internal.utils.BotUtilsKt$httpGet$2.invokeSuspend(BotUtils.kt:90)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
````
`GroupActive`的实现好像有些问题，暂且改名等待后期修复了

**Comment by HatoYuze** [comment]
访问脱敏前的`https://qun.qq.com/cgi-bin/honorv2/honor_title_list?group_code=5*******7&request_type=2&g_tk=1********0`
得到`404`错误结果 我怀疑是不是腾讯换接口了
