### ISSUE TITLE
 Can not fetch groups list

### ISSUE THREAD

**Issue by KanatoKun** [MrXiaoM/Overflow#72]
### 问题描述

使用时出现该现象无法处理群消息中的内容，私聊正常，报错如下

2024-07-23 09:39:57 W/Onebot: 请求失败: [get_group_list] Timed out waiting for 10000 ms。如果你认为这是 Overflow 的问题
，请带上 logs/onebot 中的日志来反馈。
2024-07-23 09:39:57 W/Bot.330328154: Can not fetch groups list.

### 复现

更换账号、shamrock版本，overflow版本后均无效果

### Overflow 版本

overflow-2.16.0-b2f275f

### 其他组件版本

OpenShamrock 1.1.1
OpenShamrock1.0.8

### 系统日志

```text
===================================[ Mirai console 2.16.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2024-07-23 09:39:46 I/main: Backend: version 2.16.0, built on 2023-10-20 06:28:10.
2024-07-23 09:39:46 I/main: Frontend Terminal: version 2.16.0, provided by Mamoe Technologies
2024-07-23 09:39:46 I/main: Welcome to visit https://mirai.mamoe.net/
2024-07-23 09:39:46 I/plugin: Successfully loaded plugin Chat Command v0.6.0
2024-07-23 09:39:46 I/plugin: Successfully loaded plugin Minecraft MOTD Fetcher v1.1.19
2024-07-23 09:39:46 I/plugin: Successfully loaded plugin NetworkTools v1.1.2
2024-07-23 09:39:46 I/plugin: Successfully loaded plugin Reporter v1.6.1
2024-07-23 09:39:47 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2024-07-23 09:39:47 I/Minecraft MOTD Fetcher: McMotd is loading
2024-07-23 09:39:47 I/NetworkTools: NetworkTools V1.1.2 loaded
2024-07-23 09:39:47 I/main: 6 plugin(s) enabled.
2024-07-23 09:39:47 I/main: mirai-console started successfully.
2024-07-23 09:39:47 I/Onebot: Overflow v2.16.0-57a113b-SNAPSHOT.1 正在运行
2024-07-23 09:39:47 I/Onebot: 连接到 WebSocket: ws://192.168.1.98:5800
2024-07-23 09:39:47 I/Onebot: ▌ 已连接到服务器 ┈━═☆
2024-07-23 09:39:47 I/Onebot: 协议端版本信息
{
  "app_full_name": "Shamrock v1.1.1.onebot.r438.36ed55d",
  "app_name": "Shamrock",
  "app_version": "1.1.1.onebot.r438.36ed55d",
  "impl": "shamrock",
  "version": "1.1.1.onebot.r438.36ed55d",
  "onebot_version": "11"
}
2024-07-23 09:39:47 V/Bot.330328154: 2 friends loaded.
2024-07-23 09:39:57 W/Onebot: 请求失败: [get_group_list] Timed out waiting for 10000 ms。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-07-23 09:39:57 W/Bot.330328154: Can not fetch groups list.
2024-07-23 09:39:57 V/Bot.330328154: Event: BotOnlineEvent(bot=Bot(330328154))
```

### 网络日志

```text
2024-07-23 09:39:47 I/Onebot: 连接到 WebSocket: ws://192.168.1.98:5800
2024-07-23 09:39:47 I/Onebot: ▌ 已连接到服务器 ┈━═☆
2024-07-23 09:39:47 D/Onebot: [Send] --> {"action":"get_version_info","echo":0}
2024-07-23 09:39:47 D/Onebot: [Recv] <-- {"time":1721698786,"self_id":330328154,"post_type":"meta_event","meta_event_type":"lifecycle","sub_type":"connect","status":{"self":{"platform":"qq","user_id":330328154},"online":true,"good":true,"qq.status":"正常"},"interval":15000}
2024-07-23 09:39:47 D/Onebot: [Recv] <-- {"status":"ok","retcode":0,"data":{"app_full_name":"Shamrock v1.1.1.onebot.r438.36ed55d","app_name":"Shamrock","app_version":"1.1.1.onebot.r438.36ed55d","impl":"shamrock","version":"1.1.1.onebot.r438.36ed55d","onebot_version":"11"},"echo":0}
2024-07-23 09:39:47 I/Onebot: 协议端版本信息
{
  "app_full_name": "Shamrock v1.1.1.onebot.r438.36ed55d",
  "app_name": "Shamrock",
  "app_version": "1.1.1.onebot.r438.36ed55d",
  "impl": "shamrock",
  "version": "1.1.1.onebot.r438.36ed55d",
  "onebot_version": "11"
}
2024-07-23 09:39:47 D/Onebot: [Send] --> {"action":"get_login_info","echo":1}
2024-07-23 09:39:47 D/Onebot: [Recv] <-- {"status":"ok","retcode":0,"data":{"user_id":330328154,"nickname":"节操"},"echo":1}
2024-07-23 09:39:47 D/Onebot: [Send] --> {"action":"get_friend_list","echo":2}
2024-07-23 09:39:47 D/Onebot: [Recv] <-- {"status":"ok","retcode":0,"data":[{"user_id":66600000,"user_name":"babyQ","user_displayname":"babyQ","user_remark":"babyQ","age":0,"gender":1,"group_id":0,"platform":"MOBILE_OTHER","term_type":65794},{"user_id":330328154,"user_name":"节操","user_displayname":"","user_remark":"","age":28,"gender":0,"group_id":0,"platform":"MOBILE_HD","term_type":65805}],"echo":2}
2024-07-23 09:39:47 D/Onebot: [Send] --> {"action":"get_group_list","echo":3}
2024-07-23 09:39:57 W/Onebot: 请求失败: [get_group_list] Timed out waiting for 10000 ms。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-07-23 09:39:57 V/Onebot: Stacktrace: 
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

**Comment by MrXiaoM** [comment]
如果你的群特别多，请考虑把请求超时时间（JVM参数，用户手册有）调长，如果不多，请考虑是 Shamrock 的问题
