### ISSUE TITLE
无法处理Gensokyo的事件

### ISSUE THREAD

**Issue by IM2eR0** [MrXiaoM/Overflow#74]
### 问题描述

尝试过 正反向ws，均无效
控制台输出如下：
2024-07-28 12:52:32 I/Onebot: Overflow v2.16.0-b2f275f-SNAPSHOT.1 正在运行
2024-07-28 12:52:32 I/Onebot: 在端口 15631 开启反向 WebSocket 服务端
2024-07-28 12:52:32 I/Onebot: ▌ 反向 WebSocket 服务端已在 0.0.0.0/0.0.0.0:15631 启动
2024-07-28 12:52:32 I/Onebot: ▌ 正在等待客户端连接...
2024-07-28 12:52:33 I/Onebot: ▌ 反向 WebSocket 客户端 /127.0.0.1:64570 已连接 ┈━═☆
2024-07-28 12:52:33 I/Onebot: 协议端版本信息
{
  "app_full_name": "gensokyo",
  "app_name": "gensokyo",
  "app_version": "v1.0.0",
  "coolq_directory": "",
  "coolq_edition": "pro",
  "go-cqhttp": true,
  "plugin_build_configuration": "release",
  "plugin_build_number": 99,
  "plugin_version": "4.15.0",
  "protocol_name": 4,
  "protocol_version": "v11",
  "runtime_os": "windows",
  "runtime_version": "go1.20.2",
  "version": "v1.0.0"
}
2024-07-28 12:52:33 E/main: Exception in coroutine MiraiConsoleImplementationTerminal
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault, parameter <this>
        at kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault(Iterables.kt)
        at top.mrxiaom.overflow.internal.contact.BotWrapper.updateContacts(BotWrapper.kt:246)
        at top.mrxiaom.overflow.internal.contact.BotWrapper$updateContacts$1.invokeSuspend(BotWrapper.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2024-07-28 12:52:48 W/Overflow: 接收到的 cn.evolvefield.onebot.sdk.event.message.GroupMessageEvent 事件中，selfId = 102073826，无法从已登录的机器人列表中找到该机器人。

本人也尝试过在 Gensokyo 启用uid登录方式，也是该报错，只不过selfId后变了个数

### 复现

基本上打开就有

### Overflow 版本

b2f275f-SNAPSHOT.1

### 其他组件版本

Gensokyo Release 472/merge

### 系统日志

```text
2024-07-28 12:45:33 I/main: Starting mirai-console...
2024-07-28 12:45:33 I/main: 

===================================[ Mirai console 2.16.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2024-07-28 12:45:33 I/main: Backend: version 2.16.0, built on 2023-10-20 06:28:10.
2024-07-28 12:45:33 I/main: Frontend Terminal: version 2.16.0, provided by Mamoe Technologies
2024-07-28 12:45:33 I/main: Welcome to visit https://mirai.mamoe.net/
2024-07-28 12:45:33 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2024-07-28 12:45:34 I/main: 2 plugin(s) enabled.
2024-07-28 12:45:34 I/main: mirai-console started successfully.
2024-07-28 12:45:34 I/Onebot: Overflow v2.16.0-b2f275f-SNAPSHOT.1 正在运行
2024-07-28 12:45:34 I/Onebot: 在端口 15631 开启反向 WebSocket 服务端
2024-07-28 12:45:34 I/Onebot: ▌ 反向 WebSocket 服务端已在 0.0.0.0/0.0.0.0:15631 启动
2024-07-28 12:45:34 I/Onebot: ▌ 正在等待客户端连接...
2024-07-28 12:46:10 I/Onebot: ▌ 反向 WebSocket 客户端 /127.0.0.1:62657 已连接 ┈━═☆
2024-07-28 12:46:10 I/Onebot: 协议端版本信息
{
  "app_full_name": "gensokyo",
  "app_name": "gensokyo",
  "app_version": "v1.0.0",
  "coolq_directory": "",
  "coolq_edition": "pro",
  "go-cqhttp": true,
  "plugin_build_configuration": "release",
  "plugin_build_number": 99,
  "plugin_version": "4.15.0",
  "protocol_name": 4,
  "protocol_version": "v11",
  "runtime_os": "windows",
  "runtime_version": "go1.20.2",
  "version": "v1.0.0"
}
2024-07-28 12:46:10 E/main: Exception in coroutine MiraiConsoleImplementationTerminal
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault, parameter <this>
	at kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault(Iterables.kt)
	at top.mrxiaom.overflow.internal.contact.BotWrapper.updateContacts(BotWrapper.kt:246)
	at top.mrxiaom.overflow.internal.contact.BotWrapper$updateContacts$1.invokeSuspend(BotWrapper.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2024-07-28 12:46:19 W/Overflow: 接收到的 cn.evolvefield.onebot.sdk.event.message.GroupMessageEvent 事件中，selfId = 2854207415，无法从已登录的机器人列表中找到该机器人。
2024-07-28 12:51:30 W/console: 未知指令: /无法从已登录的机器人列表中找到该机器人, 输入 ? 获取帮助
2024-07-28 12:51:59 I/Onebot: ▌ 反向 WebSocket 客户端连接因 Connection reset 已关闭 (关闭码: ABNORMAL_CLOSE)
2024-07-28 12:52:01 I/Onebot: ▌ 反向 WebSocket 客户端 /127.0.0.1:64403 已连接 ┈━═☆
2024-07-28 12:52:15 W/Overflow: 接收到的 cn.evolvefield.onebot.sdk.event.message.GroupMessageEvent 事件中，selfId = 102073826，无法从已登录的机器人列表中找到该机器人。
2024-07-28 12:52:31 I/main: Starting mirai-console...
2024-07-28 12:52:31 I/main: 

===================================[ Mirai console 2.16.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2024-07-28 12:52:31 I/main: Backend: version 2.16.0, built on 2023-10-20 06:28:10.
2024-07-28 12:52:31 I/main: Frontend Terminal: version 2.16.0, provided by Mamoe Technologies
2024-07-28 12:52:31 I/main: Welcome to visit https://mirai.mamoe.net/
2024-07-28 12:52:32 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2024-07-28 12:52:32 I/main: 2 plugin(s) enabled.
2024-07-28 12:52:32 I/main: mirai-console started successfully.
2024-07-28 12:52:32 I/Onebot: Overflow v2.16.0-b2f275f-SNAPSHOT.1 正在运行
2024-07-28 12:52:32 I/Onebot: 在端口 15631 开启反向 WebSocket 服务端
2024-07-28 12:52:32 I/Onebot: ▌ 反向 WebSocket 服务端已在 0.0.0.0/0.0.0.0:15631 启动
2024-07-28 12:52:32 I/Onebot: ▌ 正在等待客户端连接...
2024-07-28 12:52:33 I/Onebot: ▌ 反向 WebSocket 客户端 /127.0.0.1:64570 已连接 ┈━═☆
2024-07-28 12:52:33 I/Onebot: 协议端版本信息
{
  "app_full_name": "gensokyo",
  "app_name": "gensokyo",
  "app_version": "v1.0.0",
  "coolq_directory": "",
  "coolq_edition": "pro",
  "go-cqhttp": true,
  "plugin_build_configuration": "release",
  "plugin_build_number": 99,
  "plugin_version": "4.15.0",
  "protocol_name": 4,
  "protocol_version": "v11",
  "runtime_os": "windows",
  "runtime_version": "go1.20.2",
  "version": "v1.0.0"
}
2024-07-28 12:52:33 E/main: Exception in coroutine MiraiConsoleImplementationTerminal
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault, parameter <this>
	at kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault(Iterables.kt)
	at top.mrxiaom.overflow.internal.contact.BotWrapper.updateContacts(BotWrapper.kt:246)
	at top.mrxiaom.overflow.internal.contact.BotWrapper$updateContacts$1.invokeSuspend(BotWrapper.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2024-07-28 12:52:48 W/Overflow: 接收到的 cn.evolvefield.onebot.sdk.event.message.GroupMessageEvent 事件中，selfId = 102073826，无法从已登录的机器人列表中找到该机器人。
```

**Comment by IM2eR0** [comment]
我刚才尝试了一下切换到旧版的Overflow（Overflow v2.16.0-795845b-SNAPSHOT），旧版下工作正常，新版会提示该报错，并提示无法获取到已登录的机器人。

**Comment by MrXiaoM** [comment]
未填写网络日志

**Comment by IM2eR0** [comment]
网络日志在这
`2024-07-28 12:45:34 I/Onebot: Overflow v2.16.0-b2f275f-SNAPSHOT.1 正在运行
2024-07-28 12:45:34 I/Onebot: 在端口 15631 开启反向 WebSocket 服务端
2024-07-28 12:45:34 I/Onebot: ▌ 反向 WebSocket 服务端已在 0.0.0.0/0.0.0.0:15631 启动
2024-07-28 12:45:34 I/Onebot: ▌ 正在等待客户端连接...
2024-07-28 12:46:10 I/Onebot: ▌ 反向 WebSocket 客户端 /127.0.0.1:62657 已连接 ┈━═☆
2024-07-28 12:46:10 D/Onebot: [Recv] <-- {"meta_event_type":"lifecycle","post_type":"meta_event","self_id":2854207415,"sub_type":"connect","time":1722141970}
2024-07-28 12:46:10 D/Onebot: [Send] --> {"action":"get_version_info","echo":0}
2024-07-28 12:46:10 D/Onebot: [Recv] <-- {"data":{"app_full_name":"gensokyo","app_name":"gensokyo","app_version":"v1.0.0","coolq_directory":"","coolq_edition":"pro","go-cqhttp":true,"plugin_build_configuration":"release","plugin_build_number":99,"plugin_version":"4.15.0","protocol_name":4,"protocol_version":"v11","runtime_os":"windows","runtime_version":"go1.20.2","version":"v1.0.0"},"echo":0,"message":"","retcode":0,"status":"ok"}
2024-07-28 12:46:10 I/Onebot: 协议端版本信息
{
  "app_full_name": "gensokyo",
  "app_name": "gensokyo",
  "app_version": "v1.0.0",
  "coolq_directory": "",
  "coolq_edition": "pro",
  "go-cqhttp": true,
  "plugin_build_configuration": "release",
  "plugin_build_number": 99,
  "plugin_version": "4.15.0",
  "protocol_name": 4,
  "protocol_version": "v11",
  "runtime_os": "windows",
  "runtime_version": "go1.20.2",
  "version": "v1.0.0"
}
2024-07-28 12:46:10 D/Onebot: [Send] --> {"action":"get_login_info","echo":1}
2024-07-28 12:46:10 D/Onebot: [Recv] <-- {"data":{"nickname":"Gensokyo全域机器人","user_id":2854207415},"echo":1,"message":"","retcode":0,"status":"ok"}
2024-07-28 12:46:10 D/Onebot: [Send] --> {"action":"get_friend_list","echo":2}
2024-07-28 12:46:10 D/Onebot: [Recv] <-- {"data":null,"echo":2,"message":"","retcode":0,"status":"ok"}
2024-07-28 12:46:19 D/Onebot: [Recv] <-- {"font":0,"group_id":803726670,"message":[{"data":{"text":"/ip"},"type":"text"}],"message_id":771406991,"message_seq":0,"message_type":"group","post_type":"message","raw_message":"/ip","self_id":2854207415,"sender":{"area":"0","level":"0","nickname":"","role":"member","sex":"0","tiny_id":"","user_id":369473508},"sub_type":"normal","time":1722141979,"user_id":369473508}
2024-07-28 12:51:59 I/Onebot: ▌ 反向 WebSocket 客户端连接因 Connection reset 已关闭 (关闭码: ABNORMAL_CLOSE)
2024-07-28 12:52:01 I/Onebot: ▌ 反向 WebSocket 客户端 /127.0.0.1:64403 已连接 ┈━═☆
2024-07-28 12:52:01 D/Onebot: [Recv] <-- {"meta_event_type":"lifecycle","post_type":"meta_event","self_id":102073826,"sub_type":"connect","time":1722142321}
2024-07-28 12:52:15 D/Onebot: [Recv] <-- {"font":0,"group_id":803726670,"message":[{"data":{"text":"/ip"},"type":"text"}],"message_id":702198188,"message_seq":0,"message_type":"group","post_type":"message","raw_message":"/ip","self_id":102073826,"sender":{"area":"0","level":"0","nickname":"","role":"member","sex":"0","tiny_id":"","user_id":369473508},"sub_type":"normal","time":1722142335,"user_id":369473508}
2024-07-28 12:52:32 I/Onebot: Overflow v2.16.0-b2f275f-SNAPSHOT.1 正在运行
2024-07-28 12:52:32 I/Onebot: 在端口 15631 开启反向 WebSocket 服务端
2024-07-28 12:52:32 I/Onebot: ▌ 反向 WebSocket 服务端已在 0.0.0.0/0.0.0.0:15631 启动
2024-07-28 12:52:32 I/Onebot: ▌ 正在等待客户端连接...
2024-07-28 12:52:33 I/Onebot: ▌ 反向 WebSocket 客户端 /127.0.0.1:64570 已连接 ┈━═☆
2024-07-28 12:52:33 D/Onebot: [Send] --> {"action":"get_version_info","echo":0}
2024-07-28 12:52:33 D/Onebot: [Recv] <-- {"meta_event_type":"lifecycle","post_type":"meta_event","self_id":102073826,"sub_type":"connect","time":1722142353}
2024-07-28 12:52:33 D/Onebot: [Recv] <-- {"data":{"app_full_name":"gensokyo","app_name":"gensokyo","app_version":"v1.0.0","coolq_directory":"","coolq_edition":"pro","go-cqhttp":true,"plugin_build_configuration":"release","plugin_build_number":99,"plugin_version":"4.15.0","protocol_name":4,"protocol_version":"v11","runtime_os":"windows","runtime_version":"go1.20.2","version":"v1.0.0"},"echo":0,"message":"","retcode":0,"status":"ok"}
2024-07-28 12:52:33 I/Onebot: 协议端版本信息
{
  "app_full_name": "gensokyo",
  "app_name": "gensokyo",
  "app_version": "v1.0.0",
  "coolq_directory": "",
  "coolq_edition": "pro",
  "go-cqhttp": true,
  "plugin_build_configuration": "release",
  "plugin_build_number": 99,
  "plugin_version": "4.15.0",
  "protocol_name": 4,
  "protocol_version": "v11",
  "runtime_os": "windows",
  "runtime_version": "go1.20.2",
  "version": "v1.0.0"
}
2024-07-28 12:52:33 D/Onebot: [Send] --> {"action":"get_login_info","echo":1}
2024-07-28 12:52:33 D/Onebot: [Recv] <-- {"data":{"nickname":"Gensokyo全域机器人","user_id":102073826},"echo":1,"message":"","retcode":0,"status":"ok"}
2024-07-28 12:52:33 D/Onebot: [Send] --> {"action":"get_friend_list","echo":2}
2024-07-28 12:52:33 D/Onebot: [Recv] <-- {"data":null,"echo":2,"message":"","retcode":0,"status":"ok"}
2024-07-28 12:52:48 D/Onebot: [Recv] <-- {"font":0,"group_id":803726670,"message":[{"data":{"text":"/ip"},"type":"text"}],"message_id":843802899,"message_seq":0,"message_type":"group","post_type":"message","raw_message":"/ip","self_id":102073826,"sender":{"area":"0","level":"0","nickname":"","role":"member","sex":"0","tiny_id":"","user_id":369473508},"sub_type":"normal","time":1722142368,"user_id":369473508}
2024-07-28 12:59:37 D/Onebot: [Recv] <-- {"font":0,"group_id":803726670,"message":[{"data":{"text":"/ip"},"type":"text"}],"message_id":155246128,"message_seq":0,"message_type":"group","post_type":"message","raw_message":"/ip","self_id":102073826,"sender":{"area":"0","level":"0","nickname":"","role":"member","sex":"0","tiny_id":"","user_id":369473508},"sub_type":"normal","time":1722142777,"user_id":369473508}`

**Comment by IM2eR0** [comment]
网络日志：

2024-07-28 12:45:34 I/Onebot: Overflow v2.16.0-b2f275f-SNAPSHOT.1 正在运行
2024-07-28 12:45:34 I/Onebot: 在端口 15631 开启反向 WebSocket 服务端
2024-07-28 12:45:34 I/Onebot: ▌ 反向 WebSocket 服务端已在 0.0.0.0/0.0.0.0:15631 启动
2024-07-28 12:45:34 I/Onebot: ▌ 正在等待客户端连接...
2024-07-28 12:46:10 I/Onebot: ▌ 反向 WebSocket 客户端 /127.0.0.1:62657 已连接 ┈━═☆
2024-07-28 12:46:10 D/Onebot: [Recv] <-- {"meta_event_type":"lifecycle","post_type":"meta_event","self_id":2854207415,"sub_type":"connect","time":1722141970}
2024-07-28 12:46:10 D/Onebot: [Send] --> {"action":"get_version_info","echo":0}
2024-07-28 12:46:10 D/Onebot: [Recv] <-- {"data":{"app_full_name":"gensokyo","app_name":"gensokyo","app_version":"v1.0.0","coolq_directory":"","coolq_edition":"pro","go-cqhttp":true,"plugin_build_configuration":"release","plugin_build_number":99,"plugin_version":"4.15.0","protocol_name":4,"protocol_version":"v11","runtime_os":"windows","runtime_version":"go1.20.2","version":"v1.0.0"},"echo":0,"message":"","retcode":0,"status":"ok"}
2024-07-28 12:46:10 I/Onebot: 协议端版本信息
{
  "app_full_name": "gensokyo",
  "app_name": "gensokyo",
  "app_version": "v1.0.0",
  "coolq_directory": "",
  "coolq_edition": "pro",
  "go-cqhttp": true,
  "plugin_build_configuration": "release",
  "plugin_build_number": 99,
  "plugin_version": "4.15.0",
  "protocol_name": 4,
  "protocol_version": "v11",
  "runtime_os": "windows",
  "runtime_version": "go1.20.2",
  "version": "v1.0.0"
}
2024-07-28 12:46:10 D/Onebot: [Send] --> {"action":"get_login_info","echo":1}
2024-07-28 12:46:10 D/Onebot: [Recv] <-- {"data":{"nickname":"Gensokyo全域机器人","user_id":2854207415},"echo":1,"message":"","retcode":0,"status":"ok"}
2024-07-28 12:46:10 D/Onebot: [Send] --> {"action":"get_friend_list","echo":2}
2024-07-28 12:46:10 D/Onebot: [Recv] <-- {"data":null,"echo":2,"message":"","retcode":0,"status":"ok"}
2024-07-28 12:46:19 D/Onebot: [Recv] <-- {"font":0,"group_id":803726670,"message":[{"data":{"text":"/ip"},"type":"text"}],"message_id":771406991,"message_seq":0,"message_type":"group","post_type":"message","raw_message":"/ip","self_id":2854207415,"sender":{"area":"0","level":"0","nickname":"","role":"member","sex":"0","tiny_id":"","user_id":369473508},"sub_type":"normal","time":1722141979,"user_id":369473508}
2024-07-28 12:51:59 I/Onebot: ▌ 反向 WebSocket 客户端连接因 Connection reset 已关闭 (关闭码: ABNORMAL_CLOSE)
2024-07-28 12:52:01 I/Onebot: ▌ 反向 WebSocket 客户端 /127.0.0.1:64403 已连接 ┈━═☆
2024-07-28 12:52:01 D/Onebot: [Recv] <-- {"meta_event_type":"lifecycle","post_type":"meta_event","self_id":102073826,"sub_type":"connect","time":1722142321}
2024-07-28 12:52:15 D/Onebot: [Recv] <-- {"font":0,"group_id":803726670,"message":[{"data":{"text":"/ip"},"type":"text"}],"message_id":702198188,"message_seq":0,"message_type":"group","post_type":"message","raw_message":"/ip","self_id":102073826,"sender":{"area":"0","level":"0","nickname":"","role":"member","sex":"0","tiny_id":"","user_id":369473508},"sub_type":"normal","time":1722142335,"user_id":369473508}
2024-07-28 12:52:32 I/Onebot: Overflow v2.16.0-b2f275f-SNAPSHOT.1 正在运行
2024-07-28 12:52:32 I/Onebot: 在端口 15631 开启反向 WebSocket 服务端
2024-07-28 12:52:32 I/Onebot: ▌ 反向 WebSocket 服务端已在 0.0.0.0/0.0.0.0:15631 启动
2024-07-28 12:52:32 I/Onebot: ▌ 正在等待客户端连接...
2024-07-28 12:52:33 I/Onebot: ▌ 反向 WebSocket 客户端 /127.0.0.1:64570 已连接 ┈━═☆
2024-07-28 12:52:33 D/Onebot: [Send] --> {"action":"get_version_info","echo":0}
2024-07-28 12:52:33 D/Onebot: [Recv] <-- {"meta_event_type":"lifecycle","post_type":"meta_event","self_id":102073826,"sub_type":"connect","time":1722142353}
2024-07-28 12:52:33 D/Onebot: [Recv] <-- {"data":{"app_full_name":"gensokyo","app_name":"gensokyo","app_version":"v1.0.0","coolq_directory":"","coolq_edition":"pro","go-cqhttp":true,"plugin_build_configuration":"release","plugin_build_number":99,"plugin_version":"4.15.0","protocol_name":4,"protocol_version":"v11","runtime_os":"windows","runtime_version":"go1.20.2","version":"v1.0.0"},"echo":0,"message":"","retcode":0,"status":"ok"}
2024-07-28 12:52:33 I/Onebot: 协议端版本信息
{
  "app_full_name": "gensokyo",
  "app_name": "gensokyo",
  "app_version": "v1.0.0",
  "coolq_directory": "",
  "coolq_edition": "pro",
  "go-cqhttp": true,
  "plugin_build_configuration": "release",
  "plugin_build_number": 99,
  "plugin_version": "4.15.0",
  "protocol_name": 4,
  "protocol_version": "v11",
  "runtime_os": "windows",
  "runtime_version": "go1.20.2",
  "version": "v1.0.0"
}
2024-07-28 12:52:33 D/Onebot: [Send] --> {"action":"get_login_info","echo":1}
2024-07-28 12:52:33 D/Onebot: [Recv] <-- {"data":{"nickname":"Gensokyo全域机器人","user_id":102073826},"echo":1,"message":"","retcode":0,"status":"ok"}
2024-07-28 12:52:33 D/Onebot: [Send] --> {"action":"get_friend_list","echo":2}
2024-07-28 12:52:33 D/Onebot: [Recv] <-- {"data":null,"echo":2,"message":"","retcode":0,"status":"ok"}
2024-07-28 12:52:48 D/Onebot: [Recv] <-- {"font":0,"group_id":803726670,"message":[{"data":{"text":"/ip"},"type":"text"}],"message_id":843802899,"message_seq":0,"message_type":"group","post_type":"message","raw_message":"/ip","self_id":102073826,"sender":{"area":"0","level":"0","nickname":"","role":"member","sex":"0","tiny_id":"","user_id":369473508},"sub_type":"normal","time":1722142368,"user_id":369473508}
2024-07-28 12:59:37 D/Onebot: [Recv] <-- {"font":0,"group_id":803726670,"message":[{"data":{"text":"/ip"},"type":"text"}],"message_id":155246128,"message_seq":0,"message_type":"group","post_type":"message","raw_message":"/ip","self_id":102073826,"sender":{"area":"0","level":"0","nickname":"","role":"member","sex":"0","tiny_id":"","user_id":369473508},"sub_type":"normal","time":1722142777,"user_id":369473508}

**Comment by MrXiaoM** [comment]
```
[Send] --> {"action":"get_friend_list","echo":2}
[Recv] <-- {"data":null,"echo":2,"message":"","retcode":0,"status":"ok"}
```
好，知道了，非标准返回结果
