### ISSUE TITLE
消息发送失败

### ISSUE THREAD

**Issue by HanamiSeishin** [MrXiaoM/Overflow#75]
### 问题描述

overflow发送消息未产生报错日志，llonebot无日志，starbot提示发送消息失败

### 复现

问题产生原因未知，重启overflow后能恢复正常，运行一段时间后概率发生该问题

### Overflow 版本

b2f275f

### 其他组件版本

starbot 2.0.10
mirai-api-http-2.10.0
llonebot 3.27.3
java 17

### 系统日志

```text
2024-07-29 16:50:14 V/Bot.2725480293: Group(778011202) <- 东爱璃Lovely 转发了动态
https://t.bilibili.com/959515442224824341
[overflow:image,url=base64://iVBORw0KGgoAAAANSUhEUgA... (png, about 492.04 KB)
```

### 网络日志

```text
该时间点无相关日志
上传完整日志文件
```

### 补充信息

starbot日志：
2024-07-29 16:47:51.836 | INFO     | starbot.core.room:417 | [动态更新] 东爱璃Lovely
2024-07-29 16:47:53.393 | ERROR    | starbot.core.sender:199 | 消息推送模块异常
Traceback (most recent call last):

  File "/home/starbot/starbot/core/sender.py", line 322, in __send_push_message
    await self.send_message(Message(id=target.id, content=message, type=target.type))
          │    │            │          │      │           │             │      └ <PushType.Group: 1>
          │    │            │          │      │           │             └ PushTarget(id=778011202, type=<PushType.Group: 1>, live_on=LiveOn(enabled=True, message='{uname} 正在直播 {title}\n{url}\n{cover}...
          │    │            │          │      │           └ '东爱璃Lovely 转发了动态\nhttps://t.bilibili.com/959514888156217361\n{base64pic=iVBORw0KGgoAAAANSUhEUgAAAuQAAAcLCAYAAADyjqaVAAEAAElEQ...
          │    │            │          │      └ 778011202
          │    │            │          └ PushTarget(id=778011202, type=<PushType.Group: 1>, live_on=LiveOn(enabled=True, message='{uname} 正在直播 {title}\n{url}\n{cover}...
          │    │            └ <class 'starbot.core.model.Message'>
          │    └ <function Bot.send_message at 0x7fa0615080d0>
          └ Bot(qq=2725480293, ups=[Up(uid=179418, targets=[PushTarget(id=934123315, type=<PushType.Group: 1>, live_on=LiveOn(enabled=Tru...

> File "/home/starbot/starbot/core/sender.py", line 170, in send_message
    await self.__bot.send_group_message(msg.id, message)
          │                             │   │   └ MessageChain([Plain(text='东爱璃Lovely 转发了动态\nhttps://t.bilibili.com/959514888156217361\n'), Image(base64='iVBORw0KGgoAAAANSUhEU...
          │                             │   └ 778011202
          │                             └ Message(id=778011202, content='东爱璃Lovely 转发了动态\nhttps://t.bilibili.com/959514888156217361\n{base64pic=iVBORw0KGgoAAAANSUhEUgA...
          └ Bot(qq=2725480293, ups=[Up(uid=179418, targets=[PushTarget(id=934123315, type=<PushType.Group: 1>, live_on=LiveOn(enabled=Tru...

  File "/usr/local/python3/lib/python3.10/site-packages/graia/ariadne/app.py", line 1703, in send_group_message
    result = await self.connection.call(
                   │    │          └ <function ConnectionInterface.call at 0x7fa0ca9d63b0>
                   │    └ <graia.ariadne.connection.ConnectionInterface object at 0x7fa06158f1c0>
                   └ <graia.ariadne.app.Ariadne object at 0x7fa06150ec50>
  File "/usr/local/python3/lib/python3.10/site-packages/graia/ariadne/connection/__init__.py", line 202, in call
    return await connection.call(command, method, params, in_session=in_session)
                 │          │    │        │       │                  └ True
                 │          │    │        │       └ {'target': 778011202, 'messageChain': [{'type': 'Plain', 'text': '东爱璃Lovely 转发了动态\nhttps://t.bilibili.com/959514888156217361\...
                 │          │    │        └ <CallMethod.POST: 'POST'>
                 │          │    └ 'sendGroupMessage'
                 │          └ <function WebsocketConnectionMixin.call at 0x7fa0ca9d5c60>
                 └ <WebsocketClientConnection <ConnectionStatus connected=True alive=True verified=True stage=blocking> with 2 callbacks>
  File "/usr/local/python3/lib/python3.10/site-packages/graia/ariadne/connection/ws.py", line 116, in call
    return await fut
                 └ <Future finished exception=RemoteException('网络异常: 无头客户端处发生错误, 你应该检查其输出的错误日志.', {'code': 500, 'msg': '消息发送失败，详见网络日志 (logs/oneb...

graia.ariadne.exception.RemoteException: ('网络异常: 无头客户端处发生错误, 你应该检查其输出的错误日志.', {'code': 500, 'msg': '消息发送失败，详见网络日志 (logs/onebot/*.log) 和 Onebot 实现 (LLOneBot v3.27.3) 的日志'})
2024-07-29 16:50:04.106 | INFO     | starbot.core.room:417 | [动态更新] 东爱璃Lovely
2024-07-29 16:50:14.983 | ERROR    | starbot.core.sender:199 | 消息推送模块异常
Traceback (most recent call last):

  File "/home/starbot/starbot/core/sender.py", line 322, in __send_push_message
    await self.send_message(Message(id=target.id, content=message, type=target.type))
          │    │            │          │      │           │             │      └ <PushType.Group: 1>
          │    │            │          │      │           │             └ PushTarget(id=778011202, type=<PushType.Group: 1>, live_on=LiveOn(enabled=True, message='{uname} 正在直播 {title}\n{url}\n{cover}...
          │    │            │          │      │           └ '东爱璃Lovely 转发了动态\nhttps://t.bilibili.com/959515442224824341\n{base64pic=iVBORw0KGgoAAAANSUhEUgAAAuQAAAWZCAYAAAA1vwD0AAEAAElEQ...
          │    │            │          │      └ 778011202
          │    │            │          └ PushTarget(id=778011202, type=<PushType.Group: 1>, live_on=LiveOn(enabled=True, message='{uname} 正在直播 {title}\n{url}\n{cover}...
          │    │            └ <class 'starbot.core.model.Message'>
          │    └ <function Bot.send_message at 0x7fa0615080d0>
          └ Bot(qq=2725480293, ups=[Up(uid=179418, targets=[PushTarget(id=934123315, type=<PushType.Group: 1>, live_on=LiveOn(enabled=Tru...

> File "/home/starbot/starbot/core/sender.py", line 170, in send_message
    await self.__bot.send_group_message(msg.id, message)
          │                             │   │   └ MessageChain([Plain(text='东爱璃Lovely 转发了动态\nhttps://t.bilibili.com/959515442224824341\n'), Image(base64='iVBORw0KGgoAAAANSUhEU...
          │                             │   └ 778011202
          │                             └ Message(id=778011202, content='东爱璃Lovely 转发了动态\nhttps://t.bilibili.com/959515442224824341\n{base64pic=iVBORw0KGgoAAAANSUhEUgA...
          └ Bot(qq=2725480293, ups=[Up(uid=179418, targets=[PushTarget(id=934123315, type=<PushType.Group: 1>, live_on=LiveOn(enabled=Tru...

  File "/usr/local/python3/lib/python3.10/site-packages/graia/ariadne/app.py", line 1703, in send_group_message
    result = await self.connection.call(
                   │    │          └ <function ConnectionInterface.call at 0x7fa0ca9d63b0>
                   │    └ <graia.ariadne.connection.ConnectionInterface object at 0x7fa06158f1c0>
                   └ <graia.ariadne.app.Ariadne object at 0x7fa06150ec50>
  File "/usr/local/python3/lib/python3.10/site-packages/graia/ariadne/connection/__init__.py", line 202, in call
    return await connection.call(command, method, params, in_session=in_session)
                 │          │    │        │       │                  └ True
                 │          │    │        │       └ {'target': 778011202, 'messageChain': [{'type': 'Plain', 'text': '东爱璃Lovely 转发了动态\nhttps://t.bilibili.com/959515442224824341\...
                 │          │    │        └ <CallMethod.POST: 'POST'>
                 │          │    └ 'sendGroupMessage'
                 │          └ <function WebsocketConnectionMixin.call at 0x7fa0ca9d5c60>
                 └ <WebsocketClientConnection <ConnectionStatus connected=True alive=True verified=True stage=blocking> with 2 callbacks>
  File "/usr/local/python3/lib/python3.10/site-packages/graia/ariadne/connection/ws.py", line 116, in call
    return await fut
                 └ <Future finished exception=RemoteException('网络异常: 无头客户端处发生错误, 你应该检查其输出的错误日志.', {'code': 500, 'msg': '消息发送失败，详见网络日志 (logs/oneb...

graia.ariadne.exception.RemoteException: ('网络异常: 无头客户端处发生错误, 你应该检查其输出的错误日志.', {'code': 500, 'msg': '消息发送失败，详见网络日志 (logs/onebot/*.log) 和 Onebot 实现 (LLOneBot v3.27.3) 的日志'})

网络日志：
[2024-07-29.log](https://github.com/user-attachments/files/16411222/2024-07-29.log)

**Comment by MrXiaoM** [comment]
另外我有点怀疑你传错了日志，
```
2024-07-29 16:50:14 发送了消息
```
但是网络日志里没有相应的包发出去，这是不可能的

**Comment by HanamiSeishin** [comment]
是的，在llonebot日志中没有发送记录和相关日志，是通过重启qqnt和starbot问题存在和重启overflow后问题得到解决定位到可能是overflow的问题，后续问题如果复现是否有辅助定位手段

另外发送消息成功日志如下
![image](https://github.com/user-attachments/assets/4a960a40-d60b-43a7-8b29-473d0a3a581c)
上述问题发生时没有黄色打印

**Comment by HanamiSeishin** [comment]
更换napcat之后经过一番调试发现了触发该问题的条件
![image](https://github.com/user-attachments/assets/81fde143-cb5d-4a5f-b2d3-03d2c8221786)
把napcat或者llonebot断线重连后，该问题必现，需要重启overflow才能得到解决

**Comment by Lssg97** [comment]
补充，该问题在我这里可以复现。经过如下：
