### ISSUE TITLE
连接后获取信息的报错

### ISSUE THREAD

**Issue by li09090909** [MrXiaoM/Overflow#76]
### 问题描述

大佬您好，感谢您的开发，但是本人在使用时出现了小问题
![屏幕截图 2024-07-31 115629](https://github.com/user-attachments/assets/e5dfeffc-066a-4767-86a2-041ef244a865)
经过检查，openshamrock无问题，正常获取
但是在此段收取信息报错
希望给予回复。

### 复现

第一次开启时（链接已经正确填写）

### Overflow 版本

bc70f0

### 其他组件版本

Mirai console 2.16.0 openshamrock 1.0.8 r296.e68a1ff

### 系统日志

```text
2024-07-31 11:54:54 W/Onebot: 请求失败: [get_group_list] Timed out waiting for 10000 ms。如果你认为这是 Overflow 的问题 ，请带上 logs/onebot 中的日志来反馈。
2024-07-31 11:54:54 E/main: Exception in coroutine MiraiConsoleImplementationTerminal
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault, parameter <this>
        at kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault(Iterables.kt)
        at top.mrxiaom.overflow.internal.contact.BotWrapper.updateContacts(BotWrapper.kt:279)
        at top.mrxiaom.overflow.internal.contact.BotWrapper$updateContacts$1.invokeSuspend(BotWrapper.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by MrXiaoM** [comment]
#63
