### ISSUE TITLE
发送群聊消息时报错（但似乎不影响消息正常发送）

### ISSUE THREAD

**Issue by EnchantedAI** [MrXiaoM/Overflow#78]
### 问题描述

在发送图片或者语音时，overflow日志报错：
请求失败: [send_group_msg] Timed out waiting for 10000 ms。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈
mirai会报错MessageId field required

### 复现

让bot发送图片或者语音，可能需要开启quoto引用回复

### Overflow 版本

0142120

### 其他组件版本

napcat1.7.3

### 系统日志

```text
这是bot的日志报错：
Traceback (most recent call last):
  File "miniconda3/envs/qqbot/lib/python3.9/site-packages/mirai/models/api.py", line 386, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "miniconda3/envs/qqbot/lib/python3.9/site-packages/mirai/models/api.py", line 327, in call
    return response_type.parse_obj(raw_response)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "miniconda3/envs/qqbot/lib/python3.9/site-packages/mirai/models/base.py", line 33, in __init__
    super().__init__(*args, **kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MessageResponse
messageId
  field required (type=value_error.missing)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run/aiDrawPic.py", line 49, in draw
    await bot.send(event, Image(path=path),True)
  File "miniconda3/envs/qqbot/lib/python3.9/site-packages/mirai/bot.py", line 407, in send
    response = await send_message(
  File "miniconda3/envs/qqbot/lib/python3.9/site-packages/mirai/models/api.py", line 430, in __call__
    return await self.set(*args, **kwargs)
  File "miniconda3/envs/qqbot/lib/python3.9/site-packages/mirai/models/api.py", line 398, in set
    return await self._call_api(
  File "miniconda3/envs/qqbot/lib/python3.9/site-packages/mirai/models/api.py", line 388, in _call_api
    raise ApiParametersError(e) from None
  File "miniconda3/envs/qqbot/lib/python3.9/site-packages/mirai/exceptions.py", line 70, in __init__
    errors = [f'在调用 `{model.Info.alias}` 时出错。']
```

### 网络日志

```text
2024-08-04 14:01:06 W/Onebot: 请求失败: [send_group_msg] Timed out waiting for 10000 ms。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-08-04 14:01:06 V/Onebot: Stacktrace: 
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.base/java.lang.Thread.run(Thread.java:840)
以下是NapCat的日志：
2024-08-04 14:35:43 [DEBUG] xxxxxxx | 收到正向Websocket消息 {"action":"send_group_msg","params":{"group_id":xxxxxxx,"message":[{"type":"reply","data":{"id":"-2055018767"}},{"type":"image","data":{"file":"base64://iVBORw0KGgoAAAANSUhEUgAACAAAAAgACAIAAAA9xURnAAEAAElEQVR4nEz9V7NlSZYeiC3h7lscdfW9EZERqUt0VVdXN4DGoIeYh6EZ1QNpfKWRNBp/Dx9pNg/8H+SABGmGwQwwQKvq6tKVIjL01feoLdx9rcUH3zd7MtMsIm+c2OecvV0s/9TC//bf/ScPlFUQERHMDBDBzBGFEMxUDQHRTAGAkBBRVJEdIQIoIpkBMSMiESOAiiiYpGhqKiIi5ZpIZGCI5tkZQNZshkgMagaGSGZmJmAGCGBgagCARAAGAITMziGYihqaSEYAIiRiADBVdt7MAAkMy0XUDJGICREBCJFUFYkQyQBUFQCIyEyBCAzLdcoNAJjuAwCZKQKYZABDQjMldmAGiOXSSKSqAAgIMH0BQARTBQBEBEQwKNctv5S3MDVAMDNDAwM1TSkjoA+1qZnB4xuVD0LlLzvnzBSYwbB8BjBDRAMjIgRAJEB..."}}],"auto_escape":false},"echo":14} 
2024-08-04 14:35:43 [INFO] xxxxxxxxxxxxxxx) | 获取文件类型 png /home/lighthouse/.config/QQ/NapCat/temp/0c2cdcf8-913e-40d1-af24-c9ead2893ee0 
2024-08-04 14:35:54 [DEBUG] xxxxxxx(xxxxxxxxxx) | ws 消息上报  {"time":1722753354,"self_id":xxxxxxxxx,"post_type":"meta_event","meta_event_type":"heartbeat","status":{"online":true,"good":true},"interval":30000} 
2024-08-04 14:35:58 [DEBUG] xxxxxxxxxx | ws 消息上报  {"status":"ok","retcode":0,"data":{"message_id":-1866970594},"message":"","wording":"","echo":14} 
2024-08-04 14:35:58 [INFO] xxxxxxxxxxxxx(xxxxxxxxxxx) | 发送消息 给群聊 群[xxxxxxxxxxxxx(xxxxxxxxxxxxx)] : [回复消息|id:-2055018767] [图片|https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=CgoxNzIxMzQzMzxxxxxxxxxxxx5ObWYAbvxv8S61sw-GFOYn3VmRjEv7MDIP8KKJGR6qjc2ocDUIC9owE&spec=0&rkey=CAQSKAB6JWENi5LMNXIdgeFVvPEXfwbXbP7satGO3bMR0lkyZC_itOaVhDk]
```

**Comment by MrXiaoM** [comment]
#72

**Comment by EnchantedAI** [comment]
> #72

谢谢，增大超时时间后解决了
