### ISSUE TITLE
在qq群发送文件（非图片或文字，如txt，xlsx，mp4等）发生报错

### ISSUE THREAD

**Issue by 8CBCA403** [MrXiaoM/Overflow#91]
### 问题描述

![10c19f76d8c93c21d2ec8819b7b53996](https://github.com/user-attachments/assets/626a771d-717b-4702-a620-2f00948da1ab)
从目前的信息看错误很可能是发生在OneBot处理消息的反序列化阶段，但是这个问题是由overflow的调用触发的

### 复现

在机器人所在群聊发送txt，xlsx，mp4等文件

### Overflow 版本

795845b

### 其他组件版本

"net.mamoe:mirai-console" v2.16.0 from maven-stable
"net.mamoe:mirai-console-terminal" v2.16.0 from maven-stable
"org.itxtech:mcl-addon" v2.1.1 from maven-stable
plugin MCL Addon v2.1.1
 Backend: version 2.16.0, built on 2023-10-20 06:28:10.
Frontend Terminal: version 2.16.0, provided by Mamoe Technologies

### 系统日志

```text
2024-09-02 16:58:06 W/stderr: Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalStateException
2024-09-02 16:58:06 W/stderr:   at top.mrxiaom.overflow.internal.message.OnebotMessages.getLong$overflow_core(OnebotMessages.kt:377)
2024-09-02 16:58:06 W/stderr:   at top.mrxiaom.overflow.internal.message.OnebotMessages.deserializeFromOneBotJson$overflow_core(OnebotMessages.kt:288)
2024-09-02 16:58:06 W/stderr:   at top.mrxiaom.overflow.internal.message.OnebotMessages.deserializeFromOneBot$overflow_core(OnebotMessages.kt:188)
2024-09-02 16:58:06 W/stderr:   at top.mrxiaom.overflow.internal.message.OnebotMessages.deserializeFromOneBot$overflow_core$default(OnebotMessages.kt:186)
2024-09-02 16:58:06 W/stderr:   at top.mrxiaom.overflow.internal.listener.GroupMessageListener.onMessage(group.kt:44)
2024-09-02 16:58:06 W/stderr:   at top.mrxiaom.overflow.internal.listener.GroupMessageListener.onMessage(group.kt:35)
2024-09-02 16:58:06 W/stderr:   at cn.evolvefield.onebot.client.listener.EventListenerKt.message(EventListener.kt:21)
2024-09-02 16:58:06 W/stderr:   at cn.evolvefield.onebot.client.handler.EventBus.onReceive(EventBus.kt:45)
2024-09-02 16:58:06 W/stderr:   at cn.evolvefield.onebot.client.connection.WSClient$onMessage$1.invokeSuspend(WSClient.kt:65)
2024-09-02 16:58:06 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-09-02 16:58:06 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-09-02 16:58:06 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-09-02 16:58:06 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-09-02 16:58:06 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-09-02 16:58:06 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-09-02 16:58:06 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(overflow), StandaloneCoroutine{Cancelling}@60b19e80, Dispatchers.Default]
```

### 补充信息

[2024-09-02.log](https://github.com/user-attachments/files/16835219/2024-09-02.log)

**Comment by MrXiaoM** [comment]
![QQ20240902-173455](https://github.com/user-attachments/assets/40d97c1d-e99d-4d90-a68f-e8fd1d8356fe)
Overflow 版本 0142120 没有问题
